### ISSUE TITLE
Frequent disconnect/connect issues even on localhost

### ISSUE THREAD

**Issue by Zordid** [chkr1011/MQTTnet#289] opened 2018-05-30 16:02 UTC
I am not sure why, but even when I host my broker on the exact same machine - and start my program using the ManagedClient, I have very frequent disconnects/reconnects.
Sometimes within seconds of the first connect, I lose connection - the console shows something like "The thread 0x78a4 has exited with code 0 (0x0)." and soon after that I get a Disconnect call to my delegate, followed by (a successful) reconnect.

Why is that happening? I tested several MQTT brokers, the effect is the same.

I have a .Net Core project using MQTTNet 2.7.5.

Thanks!

**Comment by chkr1011** [comment] 2018-05-30 18:37
Hi,
do you have a snippet which demonstrates this issue?
Best regards
Christian

**Comment by i8beef** [comment] 2018-06-02 08:57
Seeing similar behavior. Setup as follows:

            var optionsBuilder = new MqttClientOptionsBuilder()
                .WithTcpServer(_brokerIp, _brokerPort)
                .WithClientId(MqttClientId.ToString())
                .WithCleanSession();

            if (!string.IsNullOrEmpty(_brokerUsername) && !string.IsNullOrEmpty(_brokerPassword))
                optionsBuilder.WithCredentials(_brokerUsername, _brokerPassword);

            // Connect to MQTT
            await MqttClient.ConnectAsync(optionsBuilder.Build()).ConfigureAwait(false);

            // Log trace messages
            MqttNetGlobalLogger.LogMessagePublished += (sender, e) =>
            {
                switch (e.TraceMessage.Level)
                {
                    case MqttNetLogLevel.Error:
                        _serviceLog.LogError(e.TraceMessage.Message, e.TraceMessage.Exception);
                        break;
                    case MqttNetLogLevel.Warning:
                        _serviceLog.LogWarning(e.TraceMessage.Message);
                        break;
                    case MqttNetLogLevel.Info:
                        _serviceLog.LogInformation(e.TraceMessage.Message);
                        break;
                    case MqttNetLogLevel.Verbose:
                    default:
                        _serviceLog.LogTrace(e.TraceMessage.Message);
                        break;
                }
            };

           MqttClient.Connected += (sender, e) => _serviceLog.LogInformation("MQTT Connection established");
            MqttClient.Disconnected += (sender, e) =>
            {
                if (!_stopping)
                {
                    _serviceLog.LogInformation("MQTT Connection closed unexpectedly");
                    ApplicationLifetime.StopApplication();
                }
                else
                {
                    _serviceLog.LogInformation("MQTT Connection closed");
                }
            };

            MqttClient.ApplicationMessageReceived += Mqtt_MqttMsgPublishReceived;

It also does several subscriptions beyond this. I see random disconnects using the client against a Mosquitto broker.

**Comment by i8beef** [comment] 2018-06-02 21:54
More information from the trace log. Updated the comment above with the exact code that produces this, running in a .NET Core console application with MQTTNet 2.7.5, against a Mosquitto MQTT server.

Trying to connect with server.
Connecting [Timeout=00:00:10]
Connection with server established.
Start receiving packets.
TX >>> Connect: [ClientId=00000000-0000-0000-0000-000000000000] [Username=REDACTED] [Password=REDACTED] [KeepAlivePeriod=15] [CleanSession=True] [Timeout=00:00:10]
RX <<< ConnAck: [ConnectReturnCode=ConnectionAccepted] [IsSessionPresent=False]
MQTT connection with server established.
Connected.
Start sending keep alive packets.
TX >>> Subscribe: [PacketIdentifier=1] [TopicFilters=test@AtLeastOnce] [Timeout=00:00:10]
RX <<< SubAck: [PacketIdentifier=1] [SubscribeReturnCodes=SuccessMaximumQoS1]
Stopped sending keep alive packets.
Disconnecting [Timeout=00:00:10]
Disconnected from adapter.
Disconnected.
Stopped receiving packets.

**Comment by Zordid** [comment] 2018-06-03 18:02
My setup is as simple as your documentation:
A small program, just connecting to localhost or my IP address or any other broker I tested so far.

Run it. It will disconnect within a very short amount of time, usually within the first minute and repeat that behavior over and over again. I mean - it does reconnect, that is nice, but I doubt this is the desired behavior!

Here's my main:

        static async Task Main(string[] args)
        {
            Console.WriteLine("Starting MQTT Tester...");

            var options = new ManagedMqttClientOptionsBuilder()
                .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                .WithClientOptions(new MqttClientOptionsBuilder()
                    .WithClientId("Client1")
                    .WithTcpServer("192.168.178.100")
                    .Build())
                .Build();

            var mqttClient = new MqttFactory().CreateManagedMqttClient();
            mqttClient.Connected += 
                (s, e) => Console.WriteLine($"{DateTime.Now.ToShortTimeString()} connected.");
            mqttClient.Disconnected += 
                (s, e) => Console.WriteLine($"{DateTime.Now.ToShortTimeString()} disconnected");
            mqttClient.ApplicationMessageReceived += 
                (s, e) => Console.WriteLine($"{DateTime.Now.ToShortTimeString()} received: {e.ApplicationMessage.ConvertPayloadToString()}");
            await mqttClient.SubscribeAsync(new TopicFilterBuilder().WithTopic("my/topic").Build());
            await mqttClient.StartAsync(options);

            Console.ReadLine();
        }


Within the first minute the output looks like this:

    Starting MQTT Tester...
    20:01 connected.
    20:01 received: Hello, world!
    20:01 received: Hello, world!
    20:02 received: Hello, world!
    20:02 disconnected
    20:02 connected.

Thanks for any help!

**Comment by Zordid** [comment] 2018-06-03 20:31
Thanks to @i8beef I also added the global logging to my demo - same result.

    MQTT connection with server established.
    22:26:40 connected. MQTTnet.Client.MqttClientConnectedEventArgs 
    Connected.
    Start sending keep alive packets.
    ManagedMqttClient
    TX >>> Subscribe: [PacketIdentifier=1] [TopicFilters=my/topic@AtMostOnce] [Timeout=00:00:10]
    RX <<< SubAck: [PacketIdentifier=1] [SubscribeReturnCodes=SuccessMaximumQoS0]
    RX <<< Publish: [Topic=my/topic] [Payload.Length=13] [QoSLevel=AtMostOnce] [Dup=False] 
    [Retain=False] [PacketIdentifier=0]
    22:27:01 received: Hello, world!
    Stopped sending keep alive packets.
    Disconnecting [Timeout=00:00:10]
    Disconnected from adapter.
    Disconnected.
    22:27:02 disconnected. MQTTnet.Client.MqttClientDisconnectedEventArgs
    Stopped receiving packets.
    Trying to connect with server.

That's all I see. Tested it on Windows purely and with Mosquitto on Ubuntu + Windows MqttNet library program.

**Comment by chkr1011** [comment] 2018-06-04 18:57
Maybe this is an issue with linux brokers etc. I cannot reproduce it with the MQTTnet server. I will try to setup a test broker in ubuntu for testing.

**Comment by i8beef** [comment] 2018-06-05 04:40
Reproducable against the mosquitto test servers too: http://test.mosquitto.org/

**Comment by GieltjE** [comment] 2018-06-05 13:01
Been having issues with mosquitto for a while, intermittent and unpredictable (sometimes it stays away for a week, sometimes a few hundred exceptions in a day), see bug #161, although it doesn't appear to have much of a correlation with this problem.

Has anybody tested it against some other mqtt server software?

**Comment by chkr1011** [comment] 2018-06-05 19:18
I fixed some issues and tested with a local mosquitto server on Windows. It works (at least for a couple of minutes). I will let it run a couple of hours to see if it randomly disconnects.

I will release a new alpha (v3) including this fixes.

![image](https://user-images.githubusercontent.com/6939810/40997686-d26f53bc-6905-11e8-929f-b990a1da8ae8.png)

**Comment by GieltjE** [comment] 2018-06-05 19:37
@chkr1011 would you mind testing it while stressing all the cpu cores?

**Comment by chkr1011** [comment] 2018-06-05 19:41
All? Well I will try it 😄 I will start several clients which will send data all the time and one which does nothing.

**Comment by GieltjE** [comment] 2018-06-05 19:49
My work machine easily hogs all cores for a couple of hours with a simple mouse click, to the point that the mouse starts lagging ;)

But I noticed this behaviour way before the mouse lag starts, just a 100% flatline did the trick on the latest released version.
Thanks for testing it.

**Comment by i8beef** [comment] 2018-06-05 20:05
Cool, just be aware that it IS intermittent. Usually if it starts pinging OK for me, it'll stay up for a bit before failing. I can usually start or stop it once or twice and it'll start immediately disconnecting again. 

Once you have an alpha out Ill try it on mine too.

**Comment by i8beef** [comment] 2018-06-06 03:36
Trying your alpha4 now. Seems fairly stable thus far after several tests. Gonna let it run for a few hours and see if it remains so.

**Comment by GieltjE** [comment] 2018-06-06 09:37
alpha4 seems to have fixed the issues on our end, good work

**Comment by user-redans** [comment] 2019-03-06 07:04
I have same issue with mqtt broker on linux, randomly mqtt client send "DISCONNECT". I have no ideea why?
This is my log from broker: 

1551855063: Received PUBLISH from GateON_ID (d0, q1, r0, m821, '/GateON_A', ... (74 bytes))
1551855063: Sending PUBACK to GateON_ID (Mid: 821)
1551855063: Received PUBLISH from GateON_ID (d0, q1, r0, m822, '/GateON_A', ... (74 bytes))
1551855063: Sending PUBACK to GateON_ID (Mid: 822)
1551855064: Received DISCONNECT from GateON_ID
1551855064: Client GateON_ID disconnected.
1551855064: New connection from 192.168.111.14 on port 1883.
1551855064: New client connected from 192.168.111.14 as GateON_ID (c1, k120).
1551855064: Sending CONNACK to GateON_ID (0, 0)
1551855064: Received PUBLISH from GateON_ID (d0, q1, r0, m1, '/GateON_A', ... (74 bytes))
1551855064: Sending PUBACK to GateON_ID (Mid: 1)
1551855065: Received PUBLISH from GateON_ID (d0, q1, r0, m2, '/GateON_A', ... (74 bytes))
1551855065: Sending PUBACK to GateON_ID (Mid: 2)
1551855065: Received PUBLISH from GateON_ID (d0, q1, r0, m3, '/GateON_A', ... (74 bytes))
1551855065: Sending PUBACK to GateON_ID (Mid: 3)
1551855066: Received PUBLISH from GateON_ID (d0, q1, r0, m4, '/GateON_A', ... (74 bytes))
1551855066: Sending PUBACK to GateON_ID (Mid: 4)
1551855066: Received PUBLISH from GateON_ID (d0, q1, r0, m5, '/GateON_A', ... (74 bytes))
1551855066: Sending PUBACK to GateON_ID (Mid: 5)
1551855067: Received PUBLISH from GateON_ID (d0, q1, r0, m6, '/GateON_A', ... (74 bytes))
1551855067: Sending PUBACK to GateON_ID (Mid: 6)

**Comment by pluskal** [comment] 2019-08-18 16:44
The same issue, version MQTTNet 3.0.6, MQTT broker in eclipse-mosquitto container 1.6.4.

**Comment by muziekklas** [comment] 2020-08-05 08:06
Same here using the eclipse-mosquitto container (1.6.10), using MQTTNet V3.0.11. 
Any Idea when there is a fix available? We plan to use this in an IOT project and have a few deadlines ahead

**Comment by muziekklas** [comment] 2020-08-05 09:04
Found the issue on my end:
I've used the wrong client (ManagedClient instead of the normal one), did not set WithKeepAlivePeriod and noticed that when I remove the WithCleanSession that everything keeps working.

**Comment by Hexawolf** [comment] 2020-10-01 13:12
I am able to reproduce this not only with this library, but also with Golang and Java libraries, and they are getting disconnected from local brokers roughly at the same time - on *many* Windows machines. I am talking about more than 20 different computers as we use Mosquitto on all of them -- it seems to be a Mosquitto issue. But looking at their bug tracker, it is highly unlikely that anyone will ever care about this issue -- it is flooded with issues

**Comment by chkr1011** [comment] 2020-11-01 10:48
Since this seems to be a Mosquitto issue I will close this ticlet.

**Closed by chkr1011** 2020-11-01 10:48 UTC
Labels: bug

**Comment by usarskyy** [comment] 2022-06-25 11:18
I am a bit late with my comment but in case somebody runs into a similar issue, here is my story:
I had a very similar issue and discovered that client's credentials were used multiple times to connect from different apps. Mosquitto sees that the client has logged in once more and finishes previous sessions.
