### ISSUE TITLE
Is it Possible to Block Publishing to Certain Clients

### ISSUE THREAD

**Issue by Superskee** [chkr1011/MQTTnet#1064] opened 2021-01-20 16:30 UTC
Hello,

My team and I are working with this library, and we are wondering if something along these lines is possible.

Say you have 3 clients set up to the same port and address.

Say these 3 clients are all subscribed to the topic "Test"

Say 1 client publishes a message to "Test"

Normally all 3 clients would receive this message with the typical message handler in place.

Is there a way so that the client that publishes the message does not receive the message despite being subscribed to the topic?

Thanks for any help!

**Comment by SeppPenner** [comment] 2021-01-20 17:34
I would say no, this is not possible (At least not easily). Can you use different topics maybe?

E.g.
client 1: `/topic/identifier1`
client 2: `/topic/identifier2`
client 3: `/topic/identifier3`

All clients could subscribe to `/topic/+` and check whether their own identifier is used.

E.g. if client 1 publishes, it publishes to `/topic/identifier1`.

**On client 1:** Receives the message on `/topic/+`, checks whether the topic contains the own identifier (e.g. `if(topic.Contains("identifier1"))` --> It is contained, so we can return here as we are the sender.

**On client 2:** Receives the message on `/topic/+`, checks whether the topic contains the own identifier (e.g. `topic.Contains("identifier2")` --> It is not contained, so we can run some other action(s).

**On client 3:** Receives the message on `/topic/+`, checks whether the topic contains the own identifier (e.g. `topic.Contains("identifier3")` --> It is not contained, so we can run some other action(s).

**Comment by Superskee** [comment] 2021-01-20 18:50
That's a pretty simple to understand workaround. I'll probably end up using something like that. Thanks a lot. 

I did also find something similar to what I described talked about in this thread https://github.com/chkr1011/MQTTnet/issues/300

@chkr1011 said that it was implemented in 2.8.0 but I wasn't able to find said implementation anywhere. I might have just been looking in the wrong places though

**Comment by SeppPenner** [comment] 2021-01-20 19:31
> That's a pretty simple to understand workaround. I'll probably end up using something like that. Thanks a lot.
> 
> I did also find something similar to what I described talked about in this thread #300
> 
> @chkr1011 said that it was implemented in 2.8.0 but I wasn't able to find said implementation anywhere. I might have just been looking in the wrong places though

I guess, that's this handler: https://github.com/chkr1011/MQTTnet/wiki/Server#intercepting-application-messages

Setting `context.AcceptPublish = false;`. The problem is that this will block the publishing at all (Meaning that none of your clients would get the message). Maybe, I've missed something that @chkr1011 can clear with this issue #300, I'm not sure.

**Comment by chkr1011** [comment] 2021-01-23 09:33
@SeppPenner This correct 👍 

I close this ticket because I assume it is no longer needed.

**Closed by chkr1011** 2021-01-23 09:33 UTC
Labels: question
