### ISSUE TITLE
UAP APP not connecting

### ISSUE THREAD

**Issue by munkhuushmgl** [chkr1011/MQTTnet#602] opened 2019-04-24 01:58 UTC
Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationException' in System.Private.CoreLib.dll
### RECONNECTING FAILED ###The parameter is incorrect.

    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.17763.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>
    <MinimumVisualStudioVersion>14</MinimumVisualStudioVersion>

using google CA cert https://pki.goog/roots.pem

what could be the issue?

I used dotnet core version it worked but in UWP app it doesn't work ?

**Comment by chkr1011** [comment] 2019-04-24 18:14
Hi,
do you have a code snipped to I can try to reproduce it locally? 
Also please share the StackTrace. At the moment I can only guess.
Are you using latest 3.0.0 preview or still 2.8.x?
Best regards
Christian

**Comment by munkhuushmgl** [comment] 2019-05-03 22:31
`     public static async Task<object> StartMqttAsync(string projectId, string cloudRegion,
         string registryId, string deviceId, string privateKeyFile,
         string algorithm, string caCert, int numMsgs = 20,
         string messageType = "events",
         string mqttBridgeHostName = "mqtt.googleapis.com",
         int mqttBridgePort = 8883, int jwtExpiresMin = 20,
         int waitTime = 10)
        {
            // Create our MQTT client. The client_id is a unique string 
            // that identifies this device.For Google Cloud IoT Core, 
            // it must be in the format below.
            var clientId = $"projects/{projectId}" +
                $"/locations/{cloudRegion}" +
                $"/registries/{registryId}" +
                $"/devices/{deviceId}";



            // With Google Cloud IoT Core, the username field is ignored, 
            // and the password field is used to transmit a JWT to authorize 
            // the device.
            DateTime iat = DateTime.Now;
            var pass =CreateJwtRsa(projectId, privateKeyFile);
            Debug.WriteLine("MY PASS ---> {0}", pass);
            #region mqtt


            //MqttClientOptionsBuilder optionsBuilder = new MqttClientOptionsBuilder()
            // Create client instance, Connect to the Google MQTT bridge.

            var factory = new MqttFactory();
            var client = factory.CreateMqttClient();

            MqttClientOptionsBuilderTlsParameters param = new MqttClientOptionsBuilderTlsParameters()
            {
                SslProtocol = SslProtocols.Tls12,

                AllowUntrustedCertificates = false,
                UseTls = true,
                Certificates = new List<byte[]> { new X509Certificate(caCert).Export(X509ContentType.Cert) },
                CertificateValidationCallback = delegate { return true; },
                IgnoreCertificateChainErrors = false,
                IgnoreCertificateRevocationErrors = false

            };

            var options = new MqttClientOptionsBuilder()
                    .WithClientId(clientId)
                    .WithTcpServer(mqttBridgeHostName, 443)
                    .WithTls(param)
                    //.WithTls(true, false, false, cert.Export(X509ContentType.Cert))
                    .WithCredentials("unused", pass)
                    .WithProtocolVersion(MQTTnet.Serializer.MqttProtocolVersion.V311)
                  //  .WithCleanSession()
                    .Build();
            //MqttClient client = new MqttClient(mqttBridgeHostname, mqttBridgePort,
            //    true, x509Certificate, null, mqttSslProtocols, null)
            //{
            //    ProtocolVersion = MqttProtocolVersion.Version_3_1_1
            //};

            Debug.WriteLine("Creating the client {0}", client);
            // register to message received 
            client.ApplicationMessageReceived += (s, e) =>
            {
                Debug.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
                Debug.WriteLine($"+ Topic = {e.ApplicationMessage.Topic}");
                Debug.WriteLine($"+ Payload = {Encoding.UTF8.GetString(e.ApplicationMessage.Payload)}");
                Debug.WriteLine($"+ QoS = {e.ApplicationMessage.QualityOfServiceLevel}");
                Debug.WriteLine($"+ Retain = {e.ApplicationMessage.Retain}");
                Debug.WriteLine("");
            };



                client.Disconnected += async (s, e) =>
            {
                Debug.WriteLine("### DISCONNECTED FROM SERVER ###");
                await Task.Delay(TimeSpan.FromSeconds(5));

                try
                {
                    await client.ConnectAsync(options);
                }
                catch(Exception ex)
                {
                    Debug.WriteLine("### RECONNECTING FAILED ###" +ex.Message);
                }
            };


            client.Connected += (s, e) =>
            {
                Debug.WriteLine("### CONNECTED WITH SERVER ###");


                // This is the topic that the device will receive configuration updates on.
                string mqttConfigTopic = $"/devices/{deviceId}/config";
                // The topic that the device will receive commands on.
                string mqttCommandTopic = $"/devices/{deviceId}/commands/#";
                string mqttErrorTopic = $"/devices/{deviceId}/errors";

                string[] topics = new string[] {
                    mqttConfigTopic,
                    mqttCommandTopic,
                    mqttErrorTopic
                };


                //  Subscribe to a topics
                client.SubscribeAsync(new TopicFilterBuilder().WithTopic(topics[0]).WithAtLeastOnceQoS().Build());
                client.SubscribeAsync(new TopicFilterBuilder().WithTopic(topics[1]).WithAtMostOnceQoS().Build());
                client.SubscribeAsync(new TopicFilterBuilder().WithTopic(topics[2]).WithAtMostOnceQoS().Build());

                Debug.WriteLine("### SUBSCRIBED ###");
            };

            //    Debug.WriteLine("### CONNECTED WITH SERVER ###");



            //#endregion
            await client.ConnectAsync(options);`

**Comment by munkhuushmgl** [comment] 2019-05-03 22:33
![image](https://user-images.githubusercontent.com/45373284/57168899-c64f3300-6db8-11e9-955f-fc4ea5748cf3.png)

**Comment by chkr1011** [comment] 2019-06-24 11:50
Maybe it is the TLS encryption version? Is it set to 1.2? 

Is this ticket still relevant? If not I would like to close it.

**Comment by munkhuushmgl** [comment] 2019-06-24 19:34
Yes, it is still relevant. It is set to 1.2

I will re-run code and get back to you

Best
Mike

**Comment by SeppPenner** [comment] 2019-07-18 06:47
I will close this now due to inactivity. Feel free to re-open the issue if you have more details.

**Closed by SeppPenner** 2019-07-18 06:47 UTC
Labels: bug, more-information-needed, waiting-for-reply
