### ISSUE TITLE
Different Retain behavior when publishing on client or server

### ISSUE THREAD

**Issue by ChristianRiedl** [chkr1011/MQTTnet#112] opened 2017-11-15 19:37 UTC
I noticed that when publishing messages on the server, messages with **retain** flag  are not stored by the **MqttClientRetainedMessagesManager**. Is this assymetric behavior by design ? 
I found a workarround by directly calling **mqqtClientRetainedMessageManager.HandleMessageAsync**. It works, but I think it would be better if retained messages from clients and server are handled equal.

**Comment by chkr1011** [comment] 2017-11-15 19:53
Hi,
yes you are right. This is wrong and should work in the same way as for clients. It will be fixed.

**Comment by chkr1011** [comment] 2017-11-17 20:31
This issue is fixed in the preview version 2.5.2-rc1 (available as nuget).  Please let me know if the issue is now fixed.

**Comment by ChristianRiedl** [comment] 2017-11-18 22:52
@chkr1011 thanks, the bug is fixed for me

**Closed** 2017-11-18 22:56 UTC
Labels: bug
