### ISSUE TITLE
Publish periodly

### ISSUE THREAD

**Issue by WimmerMarkus** [chkr1011/MQTTnet#1053] opened 2021-01-01 08:43 UTC
Hello, have build a .neCore Application and want to Publish DateTimeTopic everySecond, it works for a Time then Stops then the Task  without any exception or message. the application need about 75MB of Memory (RAM) when it stops the Memory is 123MB.
To reproduce the scene i put the timespan of 10ms, after ~3000Messages stops the CallBack from the Timer.
Any Ideas?

```csharp
public async Task StartAsync(CancellationToken cancellationToken)
        {
            await mqttClient.ConnectAsync(options);
            if (!mqttClient.IsConnected)
            {
                await mqttClient.ReconnectAsync();
            }

            new Timer(BroadcastCall, null, TimeSpan.Zero, TimeSpan.FromMilliseconds(10));
        }

 private async void BroadcastCall(object state)
        {
            messageCounter++;

            var message = new MqttApplicationMessageBuilder()
              .WithTopic("Broadcast/DateTime")
              .WithPayload(new UTF8Encoding().GetBytes(DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss")))
              .WithExactlyOnceQoS()
              .Build();

            await this.mqttClient.PublishAsync(message);
            logger.LogInformation($"Messages: {messageCounter}");
        }
```

**Comment by chkr1011** [comment] 2021-01-01 10:12
Maybe no solution but please try QoS 1 instead. Then we can see if the QoS 2 implementation is the root cause.

**Comment by WimmerMarkus** [comment] 2021-01-01 11:56
what does you mean?  

`var message = new MqttApplicationMessageBuilder()
              .WithTopic("Broadcast/DateTime")
              .WithPayload(new UTF8Encoding().GetBytes(DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss")))
              **.WithQualityOfServiceLevel(MQTTnet.Protocol.MqttQualityOfServiceLevel.AtMostOnce)**
              .Build();
`
it takes the same result...

**Comment by chkr1011** [comment] 2021-01-01 14:45
Please also put some locking around the usage of the client (or a SemaphoreSlim). The problem is that you are basically starting a task every 10 ms without waiting for finish. So after some time multiple tasks are trying to send data at the same time. 

This library is NOT thread safe.

**Comment by SeppPenner** [comment] 2021-01-29 08:15
I wouldn't use a timer for this either. Maybe an infinite loop (`while(true)`) and a `Task.Delay` instead of the timer could help here:

```csharp
public async Task RunInBackground(CancellationToken cancellationToken)
{
    await mqttClient.ConnectAsync(options);

    if (!mqttClient.IsConnected)
    {
        await mqttClient.ReconnectAsync();
    }

    var messageCounter = 0;

    while (!cancellationToken.IsCancellationRequested)
    {
        messageCounter++;

        var message = new MqttApplicationMessageBuilder()
            .WithTopic("Broadcast/DateTime")
            .WithPayload(new UTF8Encoding().GetBytes(DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss")))
            .WithExactlyOnceQoS()
            .Build();

        await this.mqttClient.PublishAsync(message);
        logger.LogInformation($"Messages: {messageCounter}");
        await Task.Delay(1000);
    }
}
```

**Comment by chkr1011** [comment] 2021-02-21 10:45
I close this ticket because I assume it is fixed.

**Closed by chkr1011** 2021-02-21 10:45 UTC
Labels: question
