### ISSUE TITLE
Possible Race Condition

### ISSUE THREAD

**Issue by 1iveowl** [chkr1011/MQTTnet#45] opened 2017-09-24 23:26 UTC
I'm struggling with the RecievePackets piece of you code on UWP. The issue only arise in Release, not in Debug mode.

Things seem to works on Windows 10, but not on Windows Mobile 10. I can replicate the issue both on a physical Windows 10 Mobile device as well as the Windows 10 Emulator. I even see the issue on rare occations on Windows 10 too actually.

I've been mulling over [this piece](https://github.com/chkr1011/MQTTnet/blob/37a5dc7abefdc3878fd58f12220c8fa84baa1078/MQTTnet.Core/Client/MqttClient.cs#L425) . 

I've narrowed it down to [here](https://github.com/chkr1011/MQTTnet/blob/37a5dc7abefdc3878fd58f12220c8fa84baa1078/MQTTnet.Core/Serializer/MqttPacketReader.cs#L27).   The behaviors is really strange, which leads me to thinking that this is a Race Condition sort of issue.

The Exception logged is: 

> The I/O operation has been aborted because of either a thread exit or an application request.

... and the exception originates from [here](https://github.com/chkr1011/MQTTnet/blob/37a5dc7abefdc3878fd58f12220c8fa84baa1078/MQTTnet.Core/Serializer/MqttPacketReader.cs#L27).

I've been trying to figure out exactly what you are doing with the three threads you seem to spin up [here](https://github.com/chkr1011/MQTTnet/blob/37a5dc7abefdc3878fd58f12220c8fa84baa1078/MQTTnet.Core/Client/MqttClient.cs#L417), but it is not all that clear to me.

I always tend to get concerned when I see `Task.Run(async () => ...)` as a lot of care must be taken when going from one thread to multiple.

First of, I think that you can just make `StartProcessReceivedPacket` Async. Like this:

```csharp
private async Task StartProcessReceivedPacketAsync(MqttBasePacket packet, CancellationToken cancellationToken)
{
       await ProcessReceivedPacketAsync(packet).ConfigureAwait(false);
}
```

I've tried this, and it seems to work. Well, it doesn't solve my issue in Windows Mobile 10, but it doesn't introduce any new issues either and with this change we are down to only two thread.

Any chance that you (or we) could take a closer look at this central piece of your code where packets are received? For one, I'd like to see the code here to become more explicit and easier to follow . Is this some sort of packet receiver pump? Are you handling the order of which things are being send and received somehow?

Personally, I would have used use Reactive Extensions and maybe even some [state machine ](https://www.hanselman.com/blog/Stateless30AStateMachineLibraryForNETCore.aspx) here to keep track of if Connection is made etc, as this is exactly the sort of areas where Rx excels and tight state management matters.

**Comment by 1iveowl** [comment] 2017-09-25 14:47
I dug some deeper with Wireshark.

Look at these two recording of the traffic. 

Working:
![working](https://user-images.githubusercontent.com/12871120/30814483-a15ffe96-a210-11e7-8ac2-553ff9f841ba.png)

Failing:
![failing](https://user-images.githubusercontent.com/12871120/30814484-a17036f8-a210-11e7-8ea8-7130fdb91168.png)

Looking at the timing of the fourth TCP packet. It delayed approx. 12 sec. on the one that fails. Whereas the working connection has no such delay.

Also, this happened just before the CONNACK is send. It looks like the send logic is somehow tied up on the client end.  

What I think is happening here is that the client is connecting to the server. The service is waiting for a CONNACK, but it does come. Then the server closes the connection and the client get unstuck and starts sending the CONNACK, but of course now it is too late.

**Comment by 1iveowl** [comment] 2017-09-25 18:46
This is getting stranger by the minute. 

In this small video both the `if` and the `else` is runs?! 
![if-else](https://user-images.githubusercontent.com/12871120/30825239-84b0e98c-a232-11e7-828f-703f9eeafcb2.gif)

Quantum physics?

**Comment by chkr1011** [comment] 2017-09-26 06:47
@1iveowl I also had such problems with UWP. I had a if-statement whioch was false but still entered. It was a mess. I also have it for my home automation project. I was able to fix it by debugging "Debug"-Versions only and disable the "native toolchain". 

Related to processing messages I would like to keep the way it works now becaue if you make it async/await the internal processing is halted and if you have a longer running operation the internal thread for receiving will not receive anymore. But I see that the async await keywords inside of the _Task.Run_ can be removed.

I am not very happy in adding other libraries to this project because my goal is to have it intependent from other libraries and their release cycles. I agree that it makes things easier but I assume that this is not such a big problem which can be fixed only by adding a totally different approach in dealing with incoming messages. Especially because it works on Windows 10 Desktop there must be a plattform related difference. I also tested a lot with a UWP test app from this project and have no problems at all.

I assume we cannot add the _fush_ into the lock statement because this is not possible with _async/await_. So I asume it is correct. @JanEggers Can you maybe shed some light here?

@JanEggers Do you have maybe some idea? Maybe the issue is related to the new buffers etc.?

Best regards
Christian

**Comment by JanEggers** [comment] 2017-09-26 06:47
only thing i can say is that task.run is required because it is an async read loop that runs as long as the client is connected. if it would be awaited the connect would be completed if the client is disconnected again.

**Comment by chkr1011** [comment] 2017-09-26 06:50
@1iveowl Is this a new problem and didn't happen in a previous version?

**Comment by 1iveowl** [comment] 2017-09-26 06:51
Thank you. I've been working some more on the issue. I'm trying something new and will share when ready. 

Regarding putting the FlushAsync inside the lock, it is not. What you are doing inside the lock is composing the task. I'm only adding the FlushAsync to the composition. The Task is not run async until after the lock.

**Comment by JanEggers** [comment] 2017-09-26 07:04
> I assume we cannot add the fush into the lock statement because this is not possible with async/await. So I asume it is correct. @JanEggers Can you maybe shed some light here?

that is correct async await may not be inside lock statements, and the lock is present so just one writer has access to the stream at a time, without that i had raceconditions because packages override each other and then deserializing them failed.

**Comment by 1iveowl** [comment] 2017-09-26 07:08
> that is correct async await may not be inside lock statements, and the lock is present so just one writer has access to the stream at a time, without that i had raceconditions because packages override each other and then deserializing them failed.

The way I read the code you are composing the Task with ContinueWith inside the lock. Then you run the combined Task right after the lock. Is this the way you understand the code too? In this case I do believe that you can add both WriteAsync and FlushAsync inside the lock.

**Comment by JanEggers** [comment] 2017-09-26 08:36
yep you could also add flush inside the lock but flush does not affect the data that is send (so if a and b want to send stuff it does not matter if a flushes the stream or b flushes the stream). my understanding is that parallel calls to FlushAsync are scnchronized by the Stream.

**Comment by 1iveowl** [comment] 2017-09-26 08:50
My thinking was that if you add the `_channel.SendStream.FlushAsync` to the Task inside the `lock`, then at least you are sure that the `FlushAsync` is being added to the same `_channel` as the `WriteAsync`. 

If you add `FlushAsync` to the Task outside the `lock` then there is a risk (albeit probably rather small) that the `FlushAsync` will be related to some other `_channel` as the the `_channel` is no longer protected by the `lock`. Or?

**Comment by JanEggers** [comment] 2017-09-26 09:18
`_channel` is always the same instance eg relation from channeladapter to channel 1:1.

first i would verify that sending is really the issue. can u add logging to
https://github.com/chkr1011/MQTTnet/blob/37a5dc7abefdc3878fd58f12220c8fa84baa1078/MQTTnet.Core/Client/MqttClient.cs#L52

and before and after 
https://github.com/chkr1011/MQTTnet/blob/37a5dc7abefdc3878fd58f12220c8fa84baa1078/MQTTnet.Core/Client/MqttClient.cs#L65

to verify timing eg. that connect completes in time and send is called.

**Comment by 1iveowl** [comment] 2017-09-26 15:40
I tried to log the order. 

The order looks ok:

1. Connect

**Comment by 1iveowl** [comment] 2017-09-26 15:53
Looks like the issue is related to the awaiter [here](https://github.com/chkr1011/MQTTnet/blob/37a5dc7abefdc3878fd58f12220c8fa84baa1078/MQTTnet.Core/Client/MqttClient.cs#L325)

**Comment by 1iveowl** [comment] 2017-09-26 17:07
Can you help me here? 

I apologies my ignorance, but I have to admit that I don't understand the pattern and what is going on here with the `AddPacketAwaiter` and `TaskCompletionSource<MqttBasePacket>()`

I suppose it's a clever way to wait for the reply back from the server, I just don't understand how it works.

**Comment by chkr1011** [comment] 2017-09-26 18:07
@1iveowl The dispatcher handles several incoming messages. First the well known messages are directly handled like a ping request. Then the dispatcher used if the message was not handled before. The dispatcher is simply  a list of TaskCompletionSource index by type of packet and packet ID. The advantage is that the calling code can await the wait process for a certain package. Or the wait operation times out if a requested packet was not received. 

This is what the dispatcher is used for from a high level perspective. If you say that he code times out there must be a trace message saying that a particular message (including) details was not handled nor dispatched. Can you paste a full trace here?

**Comment by chkr1011** [comment] 2017-09-26 18:08
I remember a bug in the past with the dispatcher. The problem was that the packet was already received and the PacketAwaiter was not set up at the moment. The fix was to first setup the PacketAwaiter for the response and THEN sending the request packet.

**Comment by 1iveowl** [comment] 2017-09-26 18:12
It's the very first CONNECT that times out as illustrated by the two Wireshark messages above in this issue thread. 

Regarding the bug you mention. When was this fixed? I guess the order you outline is the current order.

I think I need to red up on TaskCompletionSource.

**Comment by chkr1011** [comment] 2017-09-26 18:12
One problem I can imagine is that the Dispatcher has a dictionary now and the key is the type of the message. In a previous version it was a List instead. So I am not sure but in theory it can happen that a type of message is received twice then the old one is overridden due to the same key. We may need a trace here to test for such situations.

**Comment by chkr1011** [comment] 2017-09-26 18:14
OK I will read this again...

**Comment by 1iveowl** [comment] 2017-09-26 18:20
If I read this code correctly then the Packet is send before the WaitForPacketAsync method is called. The methoed isn't called before the last `return` line.

```csharp
private async Task<TResponsePacket> SendAndReceiveAsync<TResponsePacket>(MqttBasePacket requestPacket) where TResponsePacket : MqttBasePacket
{
    var wait = _packetDispatcher.WaitForPacketAsync(requestPacket, typeof(TResponsePacket), _options.DefaultCommunicationTimeout);
    await _adapter.SendPacketsAsync(_options.DefaultCommunicationTimeout, _cancellationTokenSource.Token, requestPacket).ConfigureAwait(false);
    return (TResponsePacket) await wait;
}
```

Is this the bug you talk about here:

> I remember a bug in the past with the dispatcher. The problem was that the packet was already received and the PacketAwaiter was not set up at the moment. The fix was to first setup the PacketAwaiter for the response and THEN sending the request packet.

**Comment by chkr1011** [comment] 2017-09-26 18:25
But I am wondering why this is only a problem for Windows 10 Mobile... The desktop version has really no problems at all. 

I am not an expert with Wireshark so please correct me if I am wrong. The client connects without a problem and then the client wants to send the CONNECT packet but this has a delay of 12 seconds which leads to timeouts etc? If this is correct I assume the dispatcher is not the problem. Can you please post a log from the trace? I want to see whats happening exactly. The problem is that I cannot reproduce it. So you have to deliver every little peace of information :-)

**Comment by 1iveowl** [comment] 2017-09-26 18:29
I understand. But you need to help mere regarding the trace. Where do I find this or how do I create it?

**Comment by chkr1011** [comment] 2017-09-26 18:31
There is a static class called _MqttTrace_. It has a event and you can attach to it and write to the Console i.e. You will also find some example code in the test apps.

**Comment by 1iveowl** [comment] 2017-09-26 18:32
OK. Thanks.

**Comment by 1iveowl** [comment] 2017-09-26 19:27
Here is how far the trace goes, which seems to correlate with the Wireshark trace.

![trace](https://user-images.githubusercontent.com/12871120/30879903-23acd162-a301-11e7-9412-2238b1a2f9f4.png)

And here is where it seems to [throw the Exception](https://github.com/chkr1011/MQTTnet/blob/37a5dc7abefdc3878fd58f12220c8fa84baa1078/MQTTnet.Core/Client/MqttPacketDispatcher.cs#L28).

**Comment by JanEggers** [comment] 2017-09-27 01:01
can you please add datetime.now to each message so we see the timing

**Comment by chkr1011** [comment] 2017-09-27 07:03
@1iveowl This is very interesting. Assuming the messages are in the correct order (please add timestamps to the trace) the connect packet is sent and THEN the receiving is started. This is wrong. I don't know why this happends because in code the receive is started and THEN the connect packet is sent. Please test the following things:

* Use the task factory and start the receive task as _LongRunning_ not with Task.Run
* Add a short Task.Delay after the StartReceivePackets in _ConnectAsync_ of the client

Branch is OK.

**Comment by 1iveowl** [comment] 2017-09-27 07:40
Here are the three traces with time.

![trace - no wait](https://user-images.githubusercontent.com/12871120/30901350-b2ab6e1c-a367-11e7-8610-89e035d99cde.png)

Changed to long running: 
```csharp
private void StartReceivePackets(CancellationToken cancellationToken)
{
    Task.Factory.StartNew(() => ReceivePackets(cancellationToken), cancellationToken, TaskCreationOptions.LongRunning, TaskScheduler.Default);
}
```
![trace - no wait - long running](https://user-images.githubusercontent.com/12871120/30901391-d9b9cf26-a367-11e7-9b4d-99b762991a97.png)

With added 500ms delay after `StartReceivePackets`:
![trace - 500ms wait - long running](https://user-images.githubusercontent.com/12871120/30901410-eac99a3a-a367-11e7-9b00-b461af76af11.png)

**Comment by 1iveowl** [comment] 2017-09-27 07:48
For reference, here are the same observations with Windows 10 Desktop:

Here are the three traces with time.
![w10 - trace - no wait](https://user-images.githubusercontent.com/12871120/30901648-f97179b2-a368-11e7-8cf1-aa1208dc6a2c.png)

Changed to long running: 
![w10 - trace - no wait - long running](https://user-images.githubusercontent.com/12871120/30901653-0083f946-a369-11e7-942a-87387cc92510.png)


With added 500ms delay after `StartReceivePackets`:
![w10 - trace - 500ms wait - long running](https://user-images.githubusercontent.com/12871120/30901661-06d62e72-a369-11e7-8d23-cb0a24cf3577.png)

**Comment by 1iveowl** [comment] 2017-09-27 07:51
On rare occations I've also seen things fail on Windows 10 Desktop. Since it was so rare I've discharged this. However as I did the experiments above the whole things was very controlled and I saw Windows 10 Desktop fail.

This happened with no wait after `StartReceivePackets` and using `Task.Run(() => ...)`
![w10 - trace - no wait - failed](https://user-images.githubusercontent.com/12871120/30901752-5f734af6-a369-11e7-9681-5b7f2718a882.png)

I can't help thinking that there is some timing or Race Condition at play here.

**Comment by chkr1011** [comment] 2017-09-27 07:51
Thank you. Can you maybe test with the server from this project? I want to see of the server receives the CONNECT packet. Maybe it is a network problem and not a thread or implementation issue.

**Comment by 1iveowl** [comment] 2017-09-27 07:59
The test I've run are all pointing to test.mosquitto.org.

I've also tested against MQTT Mosquitto server on my local network. I'm running all on Ethernet. No wifi. 

Here's the test with broker.hivemq.com:
![local](https://user-images.githubusercontent.com/12871120/30902125-71839b5a-a36a-11e7-977e-0188113a7d36.png)

Here the test with a Mosquitto MQTT on my local network. I can access this server using `mosquitto_sub -h 192.168.0.205 -t '#'` from the very same PC:
![broker hivemq com](https://user-images.githubusercontent.com/12871120/30902053-3968aec2-a36a-11e7-9785-72e0d1a58624.png)

I am pretty comfortable that this is not a network issue. 

I can try you server, but that will have to be later as I've not used it yet and need understand how it works.

**Comment by 1iveowl** [comment] 2017-09-27 08:02
From the WireShart trace above, the remote server sends a CONNACK. Would it do this if no CONNECT was send?

The strange things is that I don't see a CONNECT in the Wireshark trace.

**Comment by 1iveowl** [comment] 2017-09-27 08:27
OK. That was easy enough. 

Here's the result:

![server](https://user-images.githubusercontent.com/12871120/30903255-71877546-a36e-11e7-809f-b4a2407f259c.png)


![client](https://user-images.githubusercontent.com/12871120/30903250-6ccd573c-a36e-11e7-9cb2-7ba3c0287db5.png)

**Comment by chkr1011** [comment] 2017-09-27 08:49
I know the flow but I want to be 100 % sure :)

I will install the emulator also on my machine in the evening. Then I can test on my own. Can you maybe try to deploy the UWP test app from this repository and test with that one?

**Comment by 1iveowl** [comment] 2017-09-27 09:57
I introduced this logging:

```csharp
public static MqttPacketHeader ReadHeaderFromSource(Stream stream, CancellationToken cancellationToken)
{
    byte fixedHeader;

    MqttTrace.Information(nameof(MqttClient), "Trying to Read fixed header byte");

    try
    {
        fixedHeader = (byte)stream.ReadByte();
    }
    catch (Exception ex)
    {

        MqttTrace.Error(nameof(MqttClient), ex, "Failed to Read fixed header byte");
        throw ex;
    }
            
    var controlPacketType = (MqttControlPacketType)(fixedHeader >> 4);
    var bodyLength = ReadBodyLengthFromSource(stream, cancellationToken);

    return new MqttPacketHeader
    {
        FixedHeader = fixedHeader,
        ControlPacketType = controlPacketType,
        BodyLength = bodyLength
    };
}
```

And got this result:
![log1](https://user-images.githubusercontent.com/12871120/30907460-f93ca91e-a37a-11e7-93a6-b2d4fb2f0966.png)

Could it be deadlocking on `fixedHeader = (byte)stream.ReadByte();

**Comment by 1iveowl** [comment] 2017-09-27 15:47
I changed `SendPacketsAsync` to this and everything works!

```csharp
public async Task SendPacketsAsync(TimeSpan timeout, CancellationToken cancellationToken, IEnumerable<MqttBasePacket> packets)
{
            
    try
    {
        byte[] buffer;

        using (var bufferStream = new MemoryStream())
        {
            foreach (var packet in packets)
            {
                MqttTrace.Information(nameof(MqttChannelCommunicationAdapter), "TX >>> {0} [Timeout={1}]", packet, timeout);

                var writeBuffer = PacketSerializer.Serialize(packet);

                bufferStream.Write(writeBuffer, 0, writeBuffer.Length);
            }
            buffer = bufferStream.ToArray();
        }

        await _channel.SendStream.WriteAsync(buffer, 0, buffer.Length, cancellationToken).ConfigureAwait(false);

        if (timeout > TimeSpan.Zero)
        {
            await _channel.SendStream.FlushAsync(cancellationToken).TimeoutAfter(timeout).ConfigureAwait(false);
        }
        else
        {
            await _channel.SendStream.FlushAsync(cancellationToken);
        }
    }
    catch (TaskCanceledException)
    {
        throw;
    }
    catch (MqttCommunicationTimedOutException)
    {
        throw;
    }
    catch (MqttCommunicationException)
    {
        throw;
    }
    catch (Exception exception)
    {
        throw new MqttCommunicationException(exception);
    }
}
```

**Comment by 1iveowl** [comment] 2017-09-27 15:51
Is the above an acceptable solution? Do you want me to create a PR?

**Comment by JanEggers** [comment] 2017-09-27 16:09
no for me it is not acceptable, the lock is gone. if there are two concurrent write operations the networkstrem gets corrupted. anyway at least we know whats the direction we have to investigate.

**Comment by 1iveowl** [comment] 2017-09-27 16:18
You are right. I would argue that the former solution with the lock had the same issue. In the original form the Task was composed with ContinueWith inside the lock, but the actual execution of the composed task was outside the lock at `await _sendTask`and hence you had the same issue with a risk of multiple concurrent threads trying to write to the stream.

What I think we need here is a ConcurrentQueue or something. If you agree I'll look at this. I've created something similar in the [Websocket Client I've created](https://github.com/1iveowl/WebsocketClientLite.PCL).

**Comment by JanEggers** [comment] 2017-09-27 16:21
it was fine by storing the sendtask and use continue with there may be only one send active at a time. i cant get the uwp testapp running on my machine :(

**Comment by chkr1011** [comment] 2017-09-27 16:36
I am wondering. I assume that the Lock is useless because the library is not thread safe at all. So you should Lock Access to it on your own.

I am thinking abt the continue with. If we move write and flush to one continuation it should be fi

**Comment by JanEggers** [comment] 2017-09-27 16:51
i am investigating on system.task.threading.channels for msg buffer which looks promising but is alpha. the idea with the lock context might be right. can you verify the original code with a separate lock object and see if that fixes the issue?

**Comment by chkr1011** [comment] 2017-09-27 16:51
The continuation is the Queue then because the Task is held in a field.

**Comment by 1iveowl** [comment] 2017-09-27 17:01
@chkr1011 The combination of the Task held in a field and locking on _channel, seem to have a queuing effect. But I'm not sure that it all crystal clear to me how it all works together. And also, the design clearly have some negative side-effect in UWP that is consistent on Windows 10 Mobile and only shows itself occasionally on Windows 10 Desktop.

@JanEggers Yes, I was thinking the same thing I will investigate.

I still think that the code would be more clear if all Stream Writes from all threads was going into one ConcurrentQueue and then being executed one by one. This is essentially what we are trying to accomplish, right?

**Comment by chkr1011** [comment] 2017-09-27 17:14
I am about 100 % Sure that we can avoid the Lock and the continuation is a suitable queueing mechanism. A separate Queue with a thread seems overkill to me because ist is similar to packet awaiter. Because the caller still needs the exception. So

**Comment by 1iveowl** [comment] 2017-09-27 18:10
If I understand the code right,  there are currently three thread being spun up [here](https://github.com/chkr1011/MQTTnet/blob/37a5dc7abefdc3878fd58f12220c8fa84baa1078/MQTTnet.Core/Client/MqttClient.cs#L415).


All three thread have code paths that lead them through: `SendPacketsAsync`.  

`SendPacketsAsync` contains code that writes to the same stream. With multiple threads trying to write to the same stream you need some way of handling concurrency. I think we agree on this?

Looking more careful at `SendPacketsAsync` I'd say it has two parts:

1) a compose part, which defines a sequence and order of the byte that go into a single message. The current mechanism used for composing this sequence is Task.ContinueWith(...).

2) an executing part, where the actual writing to the stream occurs. This current happens at `await _sendtask`. 

Step 2) is the critical one, because it is here that the sequence is run and something is being written to the Stream. Step one doesn't do anything. Step one only defines what is to be done in step 2). 

 Step 1) resides inside the lock. There are no locks involved with the second step, which is good, because locking over `await task` is an anti-pattern. 

I don't know if a ConcurrentQueue is overkill or not. I guess only performance testing will show, if throughput performance is the goal. My point was, that conceptually what we are trying to create here is some sort of a queue. A queue where only one message can be written to the Stream at a time.`Stream.WriteAsync` is not thread safe, so therefore we need to manage this concurrency somehow.

Also, we probably want the order of messages to be FIFO so that connect comes before connact etc.

Is this outline representative for what we are trying to accomplish?

**Comment by 1iveowl** [comment] 2017-09-27 18:53
You can see the same expressed in code here #47 

Let me know what you think. I've tested it for the issue at hand for UWP across Desktop and Phone.

Could be interesting understand how it performs compared to the current solution.

**Comment by chkr1011** [comment] 2017-09-27 19:26
@1iveowl Yes that is correctly explained.

I was able to install the Windows Mobile 10 Emulator and test it on my own. The UWP test app from this project works without problems. I tested it with _broker.hivemq.com_.

I have reviewed your pull request but to me it seems too much to solve the issue. I fixed it in my way in the current develop branch. I tested it with the UWP test app in the emulator again and it still works. 

Can you please test this version as well? Also with multiple threads?

@JanEggers Do you want to review my change also? In my opinion this should work even with multiple threads because the continuations are not executed in parallel. The only thing which can happen is that first 2 buffers are written and then the flush method is called 2 times in a row but I assume this is fine because at the second time there is no data or a fully written packet in the buffer.

**Comment by 1iveowl** [comment] 2017-09-27 19:34
@chkr1011 

I just tested this and unfortunately it does not work:
![waittask](https://user-images.githubusercontent.com/12871120/30933643-6d1a05ac-a3cb-11e7-923b-8204f047d31a.png)

Did you test in Release Mode? Or rather with Native Tool Chain?

**Comment by 1iveowl** [comment] 2017-09-27 19:38
Would you mind try running a single round of perf test with my suggestion? If it's slower then I agree that it is a dead end.

BTW: What is the purpose of this line? `var waitTask = _waitTask;` ?

**Comment by 1iveowl** [comment] 2017-09-27 19:38
Would you mind try running a single round of perf test with my suggestion? If it's slower then I agree that it is a dead end.

BTW: What is the purpose of this line? `var waitTask = _waitTask;` ?

**Comment by 1iveowl** [comment] 2017-09-27 19:40
I think the issue could be that _waittask is not thread safe.

**Comment by 1iveowl** [comment] 2017-09-27 19:46
@chkr1011 You said it earlier. The lock on _channel is useless. You are right. It was not _channel that was the problem.

The issue all along have been that if two thread reach `SendPacketsAsync`  at the same time, they both try to _do_ ContinueWith  on _waitTask, but since waitTask is not Thread Safe things go haywire and start locking up. For some reason this happens consistently with Windows 10 Mobile in Release Mode but only rarely with Windows 10 Desktop. 

I can't explain why you don't see it on you PC, but Race Conditions are exactly tricky because they have an probabilistic character to them.

**Comment by 1iveowl** [comment] 2017-09-27 19:50
I think that no matter how, when multiple threads are involved _Concurrency_ and _Order_ needs to be handled. _Locks_ handle concurrency and _Queues_ handles order. 

With _waitTask; order is being handled, but Thread Safe Concurrency is not.

**Comment by 1iveowl** [comment] 2017-09-27 21:01
So did a quick perf test.

Here's the latest results with ContinueWith:
![continuewith](https://user-images.githubusercontent.com/12871120/30937642-b046c200-a3d7-11e7-8b57-217ef2967c73.png)


Here's the result with the ConcurrentQueue:
![queue](https://user-images.githubusercontent.com/12871120/30937629-ac4a5630-a3d7-11e7-8d64-e4e90387bccb.png)

**Comment by JanEggers** [comment] 2017-09-28 06:22
@chkr1011 : i think it will break without the lock as there now may be multiple assignments to the task member. if you want to test concurrency enable these lines in the testcode. instead of bulk write they will send msgs in parallel. If that works than it is safe.

https://github.com/chkr1011/MQTTnet/blob/e947881acaa6a0eec196b017f68ccc07dac4e02c/Tests/MQTTnet.TestApp.NetFramework/PerformanceTest.cs#L116-L125

im still not shure why the original code breaks on win mobile.

**Comment by chkr1011** [comment] 2017-09-28 07:01
@1iveowl Can you please share your code of the app? Before accepting any solution (mine or yours or whatever) I would like to reproduce that issue. I tested the UWP test app from this project with the emulator and it works without any problems multiple times. 

I reviewed your changes with the Concurrent Queue and this is not an acceptable solution because the exceptions are hidden. If you call _PublishSync_ and another thread is already sending the code enqueus the message and then returns. If there is an exception while sending the OTHER thread will get it and throw it. Is there maybe a _while_ missing? The code checks for one item in the queue but then it returns without processing further items.

@JanEggers I am also suprised that a dead lock happens because the lock is only used for sends and not for reads.

I also believe we can remove that task etc. there completely and just lock on a higher level like _MqttClient_. I mean if we want to have this thread safe we also have to check other parts like subscribing/unsubscribing, connecting etc.

**Comment by chkr1011** [comment] 2017-09-28 07:32
@1iveowl @JanEggers I migrated the code to use a semaphore instead of a lock. With the performance test it works fine.

**Comment by 1iveowl** [comment] 2017-09-28 07:42
@chkr1011 The test code is I'm using is [here](https://github.com/1iveowl/MQTTClient.rx/tree/develop) on the Develop branch. The only difference is that I wrap the events and make the whole thing observable using System.Reactive - i.e. using [Reactive Extensions](https://msdn.microsoft.com/en-us/library/hh242985(v=vs.103).aspxl). System.Reactive is not some hobby library. It was originally made by Microsoft. In fact I think it sill is, even as it has been handed over to the .NET Foundation.

To run the Test you'll need to place the git directories  MQTTnet and MQTTClientRx side by side like this:

![dir](https://user-images.githubusercontent.com/12871120/30953959-7da972f0-a42e-11e7-8298-1f95c4e63c80.png)

@chkr1011 you'r right there is a bug in my code. The return statement need to be removed. In fact the whole thing can be simplified without the lock statements, because we actually don't need them:
```csharp
_pendingMessageQueue.Enqueue(message);

try
{

    if (_pendingMessageQueue.Count > 0 && _pendingMessageQueue.TryDequeue(out var messageFromQueue))
    {
        await stream.WriteAsync(messageFromQueue, 0, messageFromQueue.Length, cancellationToken).ConfigureAwait(false);

        if (timeout > TimeSpan.Zero)
        {
            await stream.FlushAsync(cancellationToken).TimeoutAfter(timeout).ConfigureAwait(false);
        }
        else
        {
            await stream.FlushAsync(cancellationToken);
        }
    }

}
catch (Exception)
{
    throw;
}
```
The reason being is that `_pendingMessageQueue.TryDequeue` will make sure that no two threads will ever try to write at once, because:

> ConcurrentQueue<T> handles all synchronization internally. If two threads call TryDequeue at precisely the same moment, neither operation is blocked. When a conflict is detected between two threads, one thread has to try again to retrieve the next element, and the synchronization is handled internally.
... as stated in the documentation for [ConcurrentQueue<T>.TryDequeue Method (T).
](https://msdn.microsoft.com/en-us/library/dd287208(v=vs.110).aspx)

@chkr1011 regarding locking in a higher level. Not sure that makes sense to me. Wouldn't you want to keep locks tight? In this particular case you'd want to make sure that no two writes are active on the same stream at the same time. This is exactly what the above does. No more, no less.

@chkr1011 Will look at the semaphore approach. How does it compare in terms of performance to the ConcurrentQueue approach?

**Comment by chkr1011** [comment] 2017-09-28 07:50
@1iveowl Thanks for sharing. I will test it but in the evening today. Locking on a higher level was just an idea. I just want to spread ideas. 

The semaphore is quite fast. There is no comparison with a queue because it is a different approach but it is fast as a simple lock statement.

I hope this will fix it finally :-)

**Comment by 1iveowl** [comment] 2017-09-28 07:53
@chkr1011 I just tested the Semaphore approach. I ran it 5 times without seeing any issue on the Windows 10 Mobile Emulator. Also I ran the perf test and it has the same exact performance characteristics as ConcurrentQueue. 

I think we got a winner 👍

**Comment by chkr1011** [comment] 2017-09-28 07:58
Lets wait for the results of my tests 😄

**Comment by 1iveowl** [comment] 2017-09-28 08:03
@chkr1011 Haha. I was just so excited. This thing have been haunting me for days! :-)

@JanEggers I ran your suggested multi thread test. Both the Semaphore test and the ConcurrentQueue works fine. There are no lock-ups. However to be fair the Semaphore approach does seem to have the best performance characteristics with multiple threads.

**Comment by JanEggers** [comment] 2017-09-28 08:07
+1 for semaphore looks nice and clean

**Comment by JTrotta** [comment] 2017-09-28 08:21
+1 for concurrent queue. Works perfect on win/mono and it's cleaner, readable and modern as well.

**Comment by chkr1011** [comment] 2017-09-28 16:08
My tests are running fine. I will release a new version soon. Thank you for your help here. 👍

**Closed by chkr1011** 2017-09-28 16:08 UTC

**Comment by 1iveowl** [comment] 2017-09-28 16:10
Likewise, thank you for ensuring my persistence 😉

**Comment by 1iveowl** [comment] 2017-09-28 16:10
Ensuring = enduring
