### ISSUE TITLE
Performance of UWP TCP client dramatically lower than other platforms

### ISSUE THREAD

**Issue by tiefschneeteufel** [chkr1011/MQTTnet#127] opened 2017-11-29 15:49 UTC
I have been experimenting with using MQTTnet with Unity. Win32 and Android clients built using MQTTnet work great and can cope with update rates of the order of hundreds/second. However, once I managed to coax Unity into working with MQTTnet, using both .NET and IL2CPP backends, performance is very poor. Above ~20 messages/second a  MqttCommunicationTimedOutException is thrown, and the client disconnects. The MQTTnet.TestApp.UniversalWindows test app is similarly slow although it does somewhat better, sustaining ~40 messages/second for around a minute before timing out. The broker I used for my tests was mosquitto running on a Raspberry Pi.

Why is UWP performance so poor? Is there something that can be done about it? For comparison M2MQTT performs similarly.

**Comment by chkr1011** [comment] 2017-11-29 20:14
Hi,
can you please give me some more details. Which version are you using? Nuget? Self compiled? Also sharing some trace.

The performance of .NET in Unity is in general not optimal like discussed in some threads like:
<https://forum.unity.com/threads/performance-issue-with-difference-between-ms-net-and-unity-mono-issue.313789/>

Also there are some considerations about performance of .NET code in Unity described here:
<https://developer.microsoft.com/en-us/windows/mixed-reality/performance_recommendations_for_unity>

The problem is that this library is not optimized to be used in Unity. There are lots of LINQ expressions, Lamdas etc. The guidelines also recommend using structs over classes which is not an option for this project.

If you share some performance diagnostics from the Code running in Unity we may can find some pitfalls which can be optimized.

Best regards
Christian

**Comment by tiefschneeteufel** [comment] 2017-11-29 20:45
Hello Christian,

I don't think this is specifically a Unity issue (although I can go into the gory details later). I checked out the develop branch (latest commit hash 0ee3c8e135261567ac5755aa262c586039e4a3e9) this afternoon, and tried publishing ~600 byte messages to a topic which I subscribed to using the  MQTTnet.TestApp.UniversalWindows test app from the Tests directory of the repository. After about a minute at around 40 messages/second it threw a MqttCommunicationTimedOutException.

I got a Unity client working with the IL2CPP backend (whereby IL bytecode is converted to C++) to work with the latest version of the master branch. To use the .NET backend for UWP Unity apps I used the develop branch from today, but had to downgrade the version of Microsoft.NETCore.UniversalWindowsPlatform to 5.0.0 and strip out support for WebSockets. I was then able to use the .NET 4.6 experimental support within Unity (version 2017.2.0p1-MRTP4).

I can provide more tracing and information tomorrow, but if the performance could be improved for a vanilla UWP app like MQTTnet.TestApp.UniversalWindows then that would be a good foundation from which to look at improving the Unity version. Performance for Android and within the Unity editor itself is great.

Thanks,

Joe

**Comment by chkr1011** [comment] 2017-11-30 20:05
How do you send the messages? In a batch probably. The problem is that no "KeepAlive" packet is processed when you send lots of messages in batch because the batch blocks the channel until everything is sent. This may explain the connection timeouts.

And UWP running on Window is also slow without having any relation with Unity? Which server do you use? The one from this project?

Best regards
Christian

**Comment by tiefschneeteufel** [comment] 2017-11-30 20:40
I am sending the messages using a Node.js script. The messages are not batched, but at a set interval of a certain number milliseconds (e.g. 150, 100, 50, 15, 5...,1). At a certain point they will certainly appear to batched to the subscriber, but my Node.js clients and other C# scripts can certainly handle hundreds of messages/second.

I am using mosquitto as my MQTT broker. It is running on a Raspberry Pi, which is also acting as my WiFi access point, and I am connected over WiFi.

I am trying to write Hololens apps with MQTT, but the experiments I have done most recently have been on the desktop. Perhaps the answer, as you say, is that UWP apps are slow. I would like to be able to handle at least 60 messages/second as the Hololens has a frame rate of 60 fps. For my particular use case I would actually prefer new messages to displace old ones, rather than having a queue growing until a timeout triggers a disconnect.

**Comment by chkr1011** [comment] 2017-12-01 08:06
I don't say that UWP apps are slower in general. Also please keep in mind that the UWP app in this repo is also used for testing. If you send 60 messages per second the UI is refreshing all the time which leads to long delays because it is not optimized for such loads.

**Comment by tiefschneeteufel** [comment] 2017-12-01 11:11
Hello Christian,

I just built a test application which puts negligible load on the UI thread. It calculates message statistics once a second and then dispatches this to the UI thread using `RunIdleAsync`. The standard TCP client barely manages to sustain 40 messages/second, but when I used the `MqttClientWebSocketOptions`, to connect to my MQTT broker via a WebSocket I get nearly 400 messages/second. This suggests to me that there is something slowing down the handling of messages in the UWP implementation of `MQTTTcpChannel`. I am attaching the my UWP project
[MqttUWPPerformanceApp.zip](https://github.com/chkr1011/MQTTnet/files/1521344/MqttUWPPerformanceApp.zip)
.

BTW, it would be great to have a more graceful failure mode when the message rate exceeds the clients ability to consume them. For example, dropping or sub-sampling "at most once (0)" QoS messages.

**Comment by tiefschneeteufel** [comment] 2018-04-11 20:38
The master branch?

Joe

**Comment by chkr1011** [comment] 2018-04-11 21:00
Yes or you use the latest nuget 2.7.4. It is the same version.

**Comment by chkr1011** [comment] 2018-06-05 19:43
@tiefschneeteufel I found an API for the UWP build which avoids generating useless buffers. So the performance should be much better now. Please try with version 2.8.0-alpha3 and let me know if it is faster now.

**Comment by tiefschneeteufel** [comment] 2018-06-05 19:44
Okay, that’s good to know. I’m on a different project now, but will try to
find the time to look at it.

Joe

**Comment by chkr1011** [comment] 2018-06-05 19:45
OK then I will close this ticket for now. If you need support please reopen it or create a new one.

**Closed by chkr1011** 2018-06-05 19:45 UTC
