### ISSUE TITLE
Support for client TLS certificate authentication in Broker?

### ISSUE THREAD

**Issue by fyrdude** [chkr1011/MQTTnet#426] opened 2018-10-03 06:34 UTC
Hello.
Im wondering if there is any plan to support client authentication via TLS certificate in the broker? I have looked and not found any way to do it.

**Comment by SeppPenner** [comment] 2019-06-25 08:39
@chkr1011 I don't think this is available yet. Am I right?

**Comment by SeppPenner** [comment] 2019-07-18 06:56
Oh, this is a duplicate of https://github.com/chkr1011/MQTTnet/issues/312.

**Closed by SeppPenner** 2019-07-18 06:56 UTC
Labels: documentation, duplicate, feature-request
