### ISSUE TITLE
net 5 3.0.15-rc1 MQTTnet.Exceptions.MqttCommunicationException: Authentication failed

### ISSUE THREAD

**Issue by pigwing** [chkr1011/MQTTnet#1098] opened 2021-02-19 06:52 UTC
### Describe the bug
when use 3.0.15 MQTTnet.Extensions.ManagedClient in net 5 trigger exception about **SSL Handshake failed with OpenSSL error**

### Which project is your bug related to?

- ManagedClient net5 3.0.15-rc1 version

>> [2021-02-19T06:47:41.0926064Z] [16] [MqttClient] [Error]: Error while connecting with server.
MQTTnet.Exceptions.MqttCommunicationException: Authentication failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapAndThrowException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
>> [2021-02-19T06:47:41.0953930Z] [16] [MqttClient] [Verbose]: Disconnecting [Timeout=00:00:10]
>> [2021-02-19T06:47:41.0954807Z] [16] [MqttClient] [Verbose]: Disconnected from adapter.
>> [2021-02-19T06:47:41.0955233Z] [16] [MqttClient] [Info]: Disconnected.

**Comment by chkr1011** [comment] 2021-02-19 10:59
This problem is not related to this library. The StackTrace shows that this is coming from .net 5.0.

**Comment by pigwing** [comment] 2021-02-20 01:31
@chkr1011 thank you

**Comment by SeppPenner** [comment] 2021-02-20 12:34
@chkr1011 Should we close this issue?

**Comment by chkr1011** [comment] 2021-02-21 10:15
I will close this since the root cause is coming from .net 5.0.

**Closed by chkr1011** 2021-02-21 10:15 UTC
Labels: bug
