### ISSUE TITLE
Can specific framework version builds be included in the nuget package

### ISSUE THREAD

**Issue by cjohnsbrown** [chkr1011/MQTTnet#545] opened 2019-02-06 20:30 UTC
I use this library in my project that is targeting .NET framework 4.6.1. According to the nuget page there are no dependencies for this target, however when building I get a bunch of System DLLs pulled in that are causing me versioning conflicts.  Looking at the nuspec file here I found this.

```
  <!-- .NET Framework -->
    <file src="..\Source\MQTTnet\bin\Release\net452\MQTTnet.*" target="lib\net452\"/>

    <file src="..\Source\MQTTnet\bin\Release\netstandard2.0\MQTTnet.*" target="lib\net461\"/>
    <file src="..\Source\MQTTnet\bin\Release\netstandard2.0\MQTTnet.*" target="lib\net462\"/>
    <file src="..\Source\MQTTnet\bin\Release\netstandard2.0\MQTTnet.*" target="lib\net470\"/>
    <file src="..\Source\MQTTnet\bin\Release\netstandard2.0\MQTTnet.*" target="lib\net471\"/>
    <file src="..\Source\MQTTnet\bin\Release\netstandard2.0\MQTTnet.*" target="lib\net472\"/>
  </files>
```

The Framework 4.5.2 version uses a Framework DLL that has no dependencies but all other versions use the netstandard build. I'm not very familiar with .net standard. Is there a reason  the other framework version cannot just use the dll for their specific target?

**Comment by JanEggers** [comment] 2019-02-07 07:24
duplicate of #380 see also dotnet/standard#580

**Closed by JanEggers** 2019-02-07 07:24 UTC
