### ISSUE TITLE
Client ApplicationMessageReceived performance regression in 3.0.0 and up

### ISSUE THREAD

**Issue by ben-hth** [chkr1011/MQTTnet#1039] opened 2020-11-30 05:59 UTC
### Describe the bug
Hi, I'm investigating a performance issue when receiving messages with MQTTnet.

I've found that when using versions >= 3.0.0 (including 3.0.14-rc2) that there seems to be an upper limit of roughly 112 messages/s that the client can receive. If I change back to 2.8.5 then that cap seems to be removed (I can hit 1500 messages/sec received before I hit the limits of my test publisher).

I've experienced this limit in a production application running in an Azure App Service and locally when debugging on my computer, as well as in a test console app (code below).

My production application is using the normal MQTTnet client but I can also see this behaviour using the managed client in my test app.

### Which project is your bug related to?
- Client
- ManagedClient

### To Reproduce

Create a new dotnet core console application.
Add a nuget reference to MQTTnet >= 3.0.0
Replace the contents of Program.cs with the code below.
Update the server address, username, password and topic to match your environment.
Run the program and observe the output counts. 

(You will need a separate application to publish messages to the topic you choose).

### Expected behavior
The message counts received should match the number published to the topic. With version 3.0.0+ that seems to be capped at ~112/s.

### Code example
 
```csharp
using MQTTnet;
using MQTTnet.Client;
using MQTTnet.Client.Options;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace mqttclientspeed
{
    class Program
    {
        private static int _count = 0;

        async static Task Main(string[] args)
        {
            var factory = new MqttFactory();
            var mqttClient = factory.CreateMqttClient();

            var options = new MqttClientOptionsBuilder()
                .WithClientId("mqttnetspeed")
                .WithTcpServer("#serveraddress#")
                .WithCredentials("#username#", "#password#")
                .WithCleanSession()
                .Build();

            //mqttClient.ApplicationMessageReceived += (s, e) =>    // version 2.8.5
            mqttClient.UseApplicationMessageReceivedHandler(e =>    // version 3.0.0+
            {
                Interlocked.Increment(ref _count);
            });

            //mqttClient.Connected += async (s, e) =>               // version 2.8.5
            mqttClient.UseConnectedHandler(async e =>               // version 3.0.0+
            {
                Console.WriteLine("### CONNECTED WITH SERVER ###");
                await mqttClient.SubscribeAsync("topic/+", MQTTnet.Protocol.MqttQualityOfServiceLevel.AtLeastOnce);
                Console.WriteLine("### SUBSCRIBED ###");
            });

            await mqttClient.ConnectAsync(options);

            while (true)
            {
                Console.WriteLine($"{Interlocked.Exchange(ref _count, 0)}/s");
                await Task.Delay(TimeSpan.FromSeconds(1));
            }
        }
    }
}

```

**Comment by chkr1011** [comment] 2020-12-02 19:30
Is the content of the handlers exactly the same when comparing both versions?

**Comment by ben-hth** [comment] 2020-12-02 23:31
Yes the content of the handlers is exactly the same (just incrementing a number to calculate the count/sec). The only difference is how the handlers are registered because of the change in the api between version 2 and 3.

The server was a rabbitmq cluster hosted in Azure we've been experimenting with, but I've done some testing with the benchmark application in the repo and can reproduce the performance drop between versions (although not as significant as what I was seeing with the Azure hosted service).

I've modified Tests/MQTTnet.TestApp.NetCore/PerformanceTest.cs to replace the "Hello world" payload with 6000 "#" characters (to simulate the size of the data I was testing with) and run the QoS1 test then connected to that from my sample code I posted previously. The results were that 3.0.13 can handle roughly half as many messages/s as 2.8.5.

![image](https://user-images.githubusercontent.com/65205198/100944068-8f23a380-3552-11eb-8d71-acb6e49ebcba.png)
![image](https://user-images.githubusercontent.com/65205198/100944086-9945a200-3552-11eb-8794-7558825ef820.png)





```patch
diff --git a/Tests/MQTTnet.TestApp.NetCore/PerformanceTest.cs b/Tests/MQTTnet.TestApp.NetCore/PerformanceTest.cs
index 60038ef8cda37c6d3b1a259c4fa3156cfa22126c..f88717401aaa8ed451cc070157db398d23b656ea 100644
--- a/Tests/MQTTnet.TestApp.NetCore/PerformanceTest.cs
+++ b/Tests/MQTTnet.TestApp.NetCore/PerformanceTest.cs
@@ -267,7 +267,7 @@ namespace MQTTnet.TestApp.NetCore
                 var message = new MqttApplicationMessage
                 {
                     Topic = "A/B/C",
-                    Payload = Encoding.UTF8.GetBytes("Hello World"),
+                    Payload = Encoding.UTF8.GetBytes("###############################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################"),
                     QualityOfServiceLevel = MqttQualityOfServiceLevel.AtLeastOnce
                 };
 

```

**Comment by chkr1011** [comment] 2020-12-08 19:51
That's interesting. It seems that the payload size decreases the performance. At least on my system. When using a smaller payload it works much faster.

**Comment by chkr1011** [comment] 2020-12-08 20:11
Could you do me a favour and use the following code snippet before creating the clients etc.?

```csharp
MQTTnet.Formatter.MqttPacketWriter.MaxBufferSize = 4096 * 3;
MQTTnet.Formatter.MqttPacketWriter.InitialBufferSize = 4096 * 3;
```

This should avoid useless array copies when working with large messages.

**Comment by chkr1011** [comment] 2021-02-21 10:49
I close this because I assume that the issue is fixed.

**Closed by chkr1011** 2021-02-21 10:49 UTC
Labels: bug
