### ISSUE TITLE
Stable broker connection in UWP

### ISSUE THREAD

**Issue by haeberle** [chkr1011/MQTTnet#71] opened 2017-10-22 18:38 UTC
I identified issues with my client connections and ask you about your experience or testing’s in your environments.
My configuration is as following:

Server as UWP on a Win10 Workstation
Client as UWP (subscriber) on Win10 Iot Raspi
Fhem as Client (subscriber) on Raspi
Easy ESP as client (publisher) on ESP8266

The problem is, the server closes the connections to the client after random timeout exceptions. I did the following tests:

a.)	Use a Raspi with fhem (client), Easy ESP(client) and mosquito (broker), fhem doesn’t log any issues.
b.)	Use Mqttnet as Server, Easy ESP (publisher). Fhem and Mqttnet do not report any issues 
c.)	Use Mqttnet as Server, fhem (subscriber) without publisher. Fhem and Mqttnet do not report any issues  (see log: Log_OnlyPublisher.txt)
d.)	Use Mqttnet as Server, fhem (subscriber) and EasyESP(publisher). Fhem reports broken connections and Mqttnet several Exceptions (see log Log_ESP_FhemClient.txt)
e.)	Use Mqttnet as Server, Mqttnet Client (subscriber) and EasyESP(publisher). Mqttnet Client reports broken connections and Mqttnet several Exceptions (see log Log_ESP_UWPClient.txt)

I did also tests running the MqttServer on a Raspi and use MqttBox as client and remember the issues with lost connections. 

At the beginning, I assume an performance issue in fhem or my UWP client, but with issues also with MqttBox, I assume another issue.

To explain the test and logs

The publisher sends two issues: temperature and pressure. In several cases, the subscriber receives all fine, but sometimes the server runs into an Timeout Exception.

Any ideas ? 

[Log_ESP_FhemClient.zip](https://github.com/chkr1011/MQTTnet/files/1405211/Log_ESP_FhemClient.zip)
[Log_ESP_UWPClient.zip](https://github.com/chkr1011/MQTTnet/files/1405212/Log_ESP_UWPClient.zip)
[Log_OnlyPublisher.zip](https://github.com/chkr1011/MQTTnet/files/1405213/Log_OnlyPublisher.zip)

**Comment by chkr1011** [comment] 2017-10-22 19:18
Hi,
thank you for your detailed bug report. I will investigate it deeper but for now if have some thoughts:
1) Please check the KeepAlive periods and the "DefaultCommunicationTimeout" options. Maybe they are not matching and thus connections are dropped actively
2) Maybe the buffering is the issue. Please use the stream directly without wrapping it in a BufferedStream. I remembered the invalid remaining length exceptions. I also had them. @JanEggers Do you maybe have some thoughts?

I will check the logs tomorrow and let you know what my findings are.

**Comment by JanEggers** [comment] 2017-10-23 06:50
[2017-10-21 08:49:56.476] [Information] [MqttChannelCommunicationAdapter] [5] [RX <<< MqttPublishPacket: [Topic=/outdoor/temp-pres/Pressure] [Payload=MTA0OC40NA==] [QoSLevel=AtMostOnce] [Dup=False] [Retain=False] [PacketIdentifier=0]]
[2017-10-21 08:49:56.476] [Verbose] [MqttClientSession] [5] [Client 'Net::MQTT::Message[2044]': Enqueued pending publish packet.]

what i see here is that before the timeout happens the server receives /outdoor/temp-pres/Pressure enqueues it to send but the actual tx for that message does not happen so i suppose something is breaking the client session in the server in a way that is not logged and the session is not closed. this pattern can be found multiple times in the log.

**Comment by haeberle** [comment] 2017-10-23 20:24
@chkr1011, to 1#: Id did the modifications, but no change in the results, looks that is not the issue. For 2# I'm using UWP and the TCPCannel imlementation is bases on Streams..

My understanding of the trace below is, that the server closes the connection in case the a message is incoming at the same time as a package is in the send pipeline. Maybe it is a sync or timing issue and the receiving method is stopped because to send a pending package ?

```
[2017-10-23 22:04:49.982] [Verbose] [MqttClientSession] [12] [Client 'ad1dda3870a443fb82bd15a3226b87d8': Enqueued pending publish packet.]
[2017-10-23 22:04:50.319] [Warning] [MqttClientSession] [4] [Client 'ad1dda3870a443fb82bd15a3226b87d8': Communication exception while processing client packets.]
MQTTnet.Core.Exceptions.MqttCommunicationException: An established connection was aborted by the software in your host machine.

An established connection was aborted by the software in your host machine.
 ---> System.Runtime.InteropServices.COMException: An established connection was aborted by the software in your host machine.

An established connection was aborted by the software in your host machine.

   at System.IO.StreamOperationAsyncResult.ThrowWithIOExceptionDispatchInfo(Exception e)
   at System.IO.StreamOperationAsyncResult.ProcessCompletedOperation()
   at System.IO.WinRtToNetFxStreamAdapter.EndRead(IAsyncResult asyncResult)
   at System.IO.WinRtToNetFxStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.ReadByte()
   at MQTTnet.Core.Serializer.MqttPacketReader.ReadBodyLengthFromSource(Stream stream, CancellationToken cancellationToken)
   at MQTTnet.Core.Serializer.MqttPacketReader.ReadHeaderFromSource(Stream stream, CancellationToken cancellationToken)
   at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter.<ReceiveAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter.<ReceivePacketAsync>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter.<ReceivePacketAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MQTTnet.Core.Server.MqttClientSession.<ReceivePacketsAsync>d__20.MoveNext()
```
 
Regards
Hans

**Comment by chkr1011** [comment] 2017-10-23 21:20
Thanks for the update. I was also thinking about that. I changed the Task.Run in the message queue to:

```csharp
Task.Factory.StartNew(async () => await SendPendingPublishPacketsAsync(adapter, cancellationToken), cancellationToken, TaskCreationOptions.LongRunning, TaskScheduler.Default).ConfigureAwait(false);
```

But it was only a try. Maybe this helps. The problem ist that I cannot test it on my own so I can only guess. My setup with a server and client runs and runs and runs.

Another idea is to check the keep alive on TCP socket level. Maybe this must be activated. Still only a roughly assumption. I remember that there is an option for this at the socket class.

**Comment by haeberle** [comment] 2017-10-24 06:20
Thanks for the answer. Did you test the server also with an UWP ? 
I'm asking because I did a overnight run with the MQTTnet.TestApp.NetCore and that works without any issue.

**Comment by haeberle** [comment] 2017-10-24 06:30
I did a test with the KeepAlive=true in the StreamSocketControl, it doesnt help, because it looks not that the server or client close the connection..

**Comment by chkr1011** [comment] 2017-10-24 07:07
Yes I use the UWP server for my smart home system. It runs over month without problems. But the problem is maybe new since the latest changes. Are you may using certificates or the unencrypted connection?

**Comment by chkr1011** [comment] 2017-10-24 07:08
Stupid question... SSL is not supported for UWP 😄

**Comment by chkr1011** [comment] 2017-10-24 07:14
But is it right that only the MQTTnet client has such problems? As far as I understand the log and your post Fhem client works without problems.

Can you please extend the violation exception and add the already read message header to the exception text. The body length is invalid but maybe we can see which message type it is.

**Comment by haeberle** [comment] 2017-10-24 07:17
;-) The server has issues.. the client is fine and works perfect.

Sure I will add and test

**Comment by haeberle** [comment] 2017-10-24 07:21
Which version you use a UWP server ? Maybe it is on my setup.

**Comment by chkr1011** [comment] 2017-10-24 07:49
The version I use on UWP is very old. 2.1.3 or so.

**Comment by haeberle** [comment] 2017-10-24 09:41
I did a 1h test run and with 2.1.3 it works fine, without any exception.

**Comment by JanEggers** [comment] 2017-10-24 10:54
i created i pr just now with aspnetcore package. that code also contains a minimum js sample. i dont know if that client sample has issues but if i hit refresh in the browser i get similar exceptions like you in your logs

**Comment by JanEggers** [comment] 2017-10-24 11:17
update: i added more code to the pr. the remaining length issue is fixed now. problem was that i did not add a throw if the websocket is closed.

**Comment by JanEggers** [comment] 2017-10-24 11:22
i also fixed another bug in the websocketstream that could generate index out of range exceptions while reading from the stream

**Comment by chkr1011** [comment] 2017-10-25 08:32
@haeberle Can you please retry it with the latest fixes from @JanEggers ? If it still does not work can you then go through each version and test it? Maybe we can then strip it down to several changed files.

**Comment by chkr1011** [comment] 2017-10-26 18:59
@haeberle Some update of the UWP problems. I created a UWP server which is running on my machine. Since several ours I have no exception. Can you reproduce the issue somehow without fhem etc.?

**Comment by haeberle** [comment] 2017-10-26 19:58
I closed the tests and it looks that the issued is build in in the version 2.4.0. The 2.3.1 was fine so far and not generate any exception I reported.

**Comment by haeberle** [comment] 2017-10-26 20:03
Yes, currently I'm using EasyEsp as publisher and the MqttnetClient as subscriber. The issue comes up only if a client subscribes to the topic.

**Comment by chkr1011** [comment] 2017-10-30 18:47
@haeberle @Zuendelmeister Please try it with the current _develop_ version. I extended the error message with some details and I collected some potential issues. After testing it please share the traces here. With the new data added to the exception I can maybe fix it.

**Comment by chkr1011** [comment] 2017-10-31 13:13
@haeberle @Zuendelmeister Good news! I was able to reproduce the error with a Xamarin Android App. I located some issues with closed stream returning invalid data. Please try it with the version from _develop_.

@JanEggers Can you please have a look and review my changes? I assume that problem still exists in other areas. The problem was that the -1 while reading from a Stream was not respected and thus always interpreted as 255 which leads to that strange problems.

**Comment by JanEggers** [comment] 2017-10-31 13:26
@chkr1011 changes look good maybe you should also add a test. (thinking of my system.io.pipelines rewrite i dont want to break it again in such a subtile way)

**Comment by chkr1011** [comment] 2017-10-31 13:28
Tell me more about that pipelines. Maybe interesting for the next version. But was it a separate nuget? Or part of the framework?

**Comment by JanEggers** [comment] 2017-10-31 14:31
it will be a system.* nuget. so i consider it part of the framework supported by ms. it will be released with .netcore 2.1 and compatible with net451. eta q1/q2 2018 so there may be several mqtt versions until their packages are stable and i can finalize my work on mqtt port.

here is the spec:
https://github.com/dotnet/corefxlab/blob/master/docs/specs/pipelines.md

my branch is really out of sync with current dev branch but i will redo the changes once the package gets released.

here is my work in progress:
https://github.com/JanEggers/MQTTnet/tree/system.io.pipelines

im currently at 200K - 300K msg/sec in the end to end test.
the cpu is still the bottlneck.
a single mqttCommunicationAdapter can handle 1 mio msg/sec
the new serializer can handle 5 mio msgs/sec

so i still have to figure out what is the limiting factor of the complete stack and how i can improve.

but a 10 x improvement is quite nice so far ;)

**Comment by chkr1011** [comment] 2017-10-31 14:46
Sounds really interesting. In theory. I am interested what the difference is on a lower level. 

Are all of that improvements related to pipelines only or do you have also other optimizations which may affect the current approach with Streams etc. as well?

**Comment by JanEggers** [comment] 2017-10-31 15:28
the difference on low level is the new api's around Span, Memory and Buffered IO that allow low level transformations like parsing and formatting without additional allocations/copy of buffers.  

there may be some microoptimizations we could port but id rather like wait. there is no immidate need for 10% or 20% perf gain when there will be 1000% once the new packages are awailable.

**Comment by Zuendelmeister** [comment] 2017-11-01 11:38
Hi all,

I finally was able to take a look at this. Unfortunately I cannot test this with the development branch. I added the dlls but the MqttClientFactory seems to be unknown:
![image](https://user-images.githubusercontent.com/14317353/32273111-64c60314-bf01-11e7-8f05-000351754b37.png)

Maybe my fault? I'd really like to to help out.

Best regards,
Zuendelmeister

**Comment by chkr1011** [comment] 2017-11-01 11:55
@Zuendelmeister This is OK because the API has changed. Version 2.5 has several breaking changes. But you can use the _MqttFactory_ now. It will also create a client and generating the options is now done via the _MqttClientOptionsBuilder_. You can also have a look at the TestApps. There you can see how the new API is used. Before the next release I will update the Wiki with new examples. Some APIs are already updated at the Wiki.

**Comment by Zuendelmeister** [comment] 2017-11-08 08:08
Hi @chkr1011,
ok good to know. I try to find some time to test this.
Do you have a plan when version 2.5 will be released?
Best regards,
Zuendelmeister

**Comment by chkr1011** [comment] 2017-11-08 13:03
@Zuendelmeister I hope to release 2.5 soon. I am still testing and changing some minor things etc. The classes I mentioned are all part of the _develop_ branch.

**Comment by chkr1011** [comment] 2017-11-08 23:20
I just release version 2.5. If the problem still occurs in this version please create a new ticket and we will start from the code base of 2.5.

**Closed by chkr1011** 2017-11-08 23:20 UTC
Labels: bug
