### ISSUE TITLE
Which is the reference for UseMqtt?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#440] opened 2018-10-10 12:55 UTC
Which is the reference for UseMqtt?

I'm not able to write 
`o.ListenAnyIP(1883, l => l.UseMqtt())`

To open a MQTT TCP Endpoint, I have to use the older method that is I follow this example 
 for AspNetCore 2 and my project is 2.1
https://github.com/chkr1011/MQTTnet/tree/master/Tests/MQTTnet.TestApp.AspNetCore2

**Comment by biapar** [comment] 2018-10-12 16:20
🤔

**Comment by SeppPenner** [comment] 2019-06-24 15:16
I will check this and update the documentation.

**Comment by biapar** [comment] 2019-06-25 10:17
Thanks.

**Comment by SeppPenner** [comment] 2019-06-26 09:20
Might take some time though.

**Comment by SeppPenner** [comment] 2019-06-28 15:12
This issue might go in the same direction: https://github.com/chkr1011/MQTTnet/issues/605

**Comment by SeppPenner** [comment] 2019-06-28 15:21
I can't reproduce the issue: https://github.com/mqttnettest/Issue440Test. Do you have some full code example for me? The only thing I found is the message from https://github.com/chkr1011/MQTTnet/issues/605.

**Comment by SeppPenner** [comment] 2019-07-18 05:57
I will close this now. The only issue I had was the one mentioned in https://github.com/chkr1011/MQTTnet/issues/605.

**Closed by SeppPenner** 2019-07-18 05:57 UTC
Labels: bug, support
