### ISSUE TITLE
MQTT server with Websockets and TCP together 

### ISSUE THREAD

**Issue by guptamayank** [chkr1011/MQTTnet#200] opened 2018-03-16 02:24 UTC
I am reading the usage of MQTTnet server but it is not clear how to configure a server to run Websocket and TCP clients together. In our use case TCP messages needs to forwarded to websocket clients (webapp). Your examples with aspnet core websockets leaves me confused if TCP clients will be able to connect or not?

**Comment by mircotamburini** [comment] 2018-03-27 09:14
I m also interested in usage of MQTTnet server with TCP and WebSocket together.
I try.... but i cant integrate TCP client with Websocket....  anyone help us?

**Comment by mircotamburini** [comment] 2018-03-27 09:57
i found a solution.
inject a MqttServerAdapter(new MqttNetLogger())

**Comment by biapar** [comment] 2018-04-03 08:56
@mircotamburini Is't better to use the broker server as a console application or in asp.net core 2 application to use it for a web client dashboard?

**Comment by mircotamburini** [comment] 2018-04-03 09:54
I use it in a asp.net core2 because i need to have integrated mqtt server tcp and websocket in a single bundle

**Comment by biapar** [comment] 2018-04-03 11:24
My idea is to have the broker server as a console application for scalability and manutenabily.
I’ve to build a multi customer dashboard. So my problem is to build the client into asp.net core 2. How to? Or Is better to use a mqtt js client?

**Comment by JanEggers** [comment] 2018-04-05 13:03
this is a duplicate of #175 and is fixed with  #214

**Closed by JanEggers** 2018-04-05 13:04 UTC

**Comment by dominik4545** [comment] 2020-07-23 07:39
Hey guys,
I found this issue and tried to do the same. 
Is it possible to share the code samples with us or prepare an example using MQTTnet with both TCP and WebSockets?

**Comment by Yussef77** [comment] 2020-07-23 08:18
> Hola chicos,
> encontré este problema e intenté hacer lo mismo.
> ¿Es posible compartir los ejemplos de código con nosotros o preparar un ejemplo usando MQTTnet con TCP y WebSockets?

The first thing is to develop a server with websocket. Did you get to that point?

Note: Go to https://github.com/chkr1011/MQTTnet/wiki/Tips-and-Tricks (End of page)

**Comment by dominik4545** [comment] 2020-07-27 14:17
> 
> 
> > Hola chicos,
> > encontré este problema e intenté hacer lo mismo.
> > ¿Es posible compartir los ejemplos de código con nosotros o preparar un ejemplo usando MQTTnet con TCP y WebSockets?
> 
> The first thing is to develop a server with websocket. Did you get to that point?
> 
> Note: Go to https://github.com/chkr1011/MQTTnet/wiki/Tips-and-Tricks (End of page)

Well, basically I don't know where to start :/

I implemented a "standard" mqtt-server based on the code snippets provided [here](https://github.com/chkr1011/MQTTnet/wiki/Server) which is running fine. Now my task would be to add additional support for websockets which I tried to do based on the [test application](https://github.com/chkr1011/MQTTnet/tree/ba68b1274bac9afd2e3d35c16f5658568d4b1d85/Tests/MQTTnet.TestApp.AspNetCore2) but there is no point to refer to an existing/running instance of the mqtt-server.

Do you know what I mean? Or do I need to start from a different point?
