### ISSUE TITLE
When does GC for PublishAsync happen?

### ISSUE THREAD

**Issue by archerian** [chkr1011/MQTTnet#130] opened 2017-12-01 22:27 UTC
For legacy reasons, I'm wrapping MQTTnet in a managed C++ DLL and exposing functions through it so regular C++ applications can make calls. I'm calling PublishAsync from the managed C++ wrapper function as shown below. Garbage collection doesnt seem to be happening and my calling app crashes after it exceeds 1.3GB memory usage.  The app doesn't show increasing memory if I comment out the PublishAsync function call, perhaps this is somehow hindering GC? I'm using .NET 4.6.1.

``` cpp
// Managed C++ DLL
bool ICInterfaceDll::m_SendMsg(char hostName[], char eventName[], char message[])
{
	bool retVal = false;
	try
	{
		retVal = m_InterCom->SendMsg(gcnew String(hostName), gcnew String(eventName), gcnew String(message));
	}
	catch (Exception ^e)
	{
		System::Diagnostics::Debug::WriteLine("m_SendMsg: " + e->Message);
	}
	return retVal;
}

// .NET C# DLL
public bool SendMsg(string hostName, string eventName, string message)
{
	bool retVal = false;
	if (Servers.ContainsKey(hostName))
	{
		try
		{
			Servers[hostName].PublishAsync(new MqttApplicationMessageBuilder().WithTopic(eventName).WithPayload(message).Build());
			retVal = true;
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
		}
	}
	return retVal;
}

**Comment by archerian** [comment] 2017-12-01 22:33
More details, I see from monitoring the application via Process Explorer that the Generation 2 memory used is the one that keeps increasing.

**Comment by archerian** [comment] 2017-12-02 00:53
quick test, took snapshots at each ReadKey(), this shows managed memory increasing even with automatic and forced GC. If I set the for loop to infinity it will go higher till it crashes.
``` csharp
using System;
using MQTTnet;
using MQTTnet.Core.ManagedClient;
using MQTTnet.Core.Client;
using MQTTnet.Core;

namespace MemTest
{
    class Program
    {
        static void Main(string[] args)
        {
            int i;
            Console.ReadKey();  // Snapshot 1
            string str = "fdshdjkgdhfjkgdhfjksdkghkjgsdhfjkgdhfgjkdfhgdjkfhgdjkfghdfjkghdfjkhgdjkfhgdjfkghdfjkghdjkfhgfdjk";
            
            var options = new ManagedMqttClientOptionsBuilder()
                            .WithAutoReconnectDelay(TimeSpan.FromSeconds(5))
                            .WithClientOptions(new MqttClientOptionsBuilder()
                                .WithClientId("Client1")
                                .WithTcpServer("localhost", 13571)
                                .WithTls().Build())
                            .Build();

            var mqttClient = new MqttFactory().CreateManagedMqttClient();
            mqttClient.StartAsync(options);
            for (i = 0; i < 100000; i++)
            {
                mqttClient.PublishAsync(new MqttApplicationMessageBuilder().WithTopic("HELLO").WithPayload(str).Build());
            }
            Console.ReadKey(); // Snapshot 2
        }
    }
}
```

**Comment by archerian** [comment] 2017-12-02 00:57
![image](https://user-images.githubusercontent.com/10156612/33509696-d405b7b4-d6d1-11e7-8fc5-edfe74e756d2.png)

**Comment by chkr1011** [comment] 2017-12-02 11:56
Hi thanks for sharing the issue. It is possible that you create a memory dump (with TaskManager) and attach it here. Then I can see which kind of classes are producing the high load. I hope that after zipping the dump the file will be small enough for a upload here.

**Comment by archerian** [comment] 2017-12-02 12:17
The generated fulldump files were too big for github, I have uploaded them to Amazon cloud drive at [https://www.amazon.com/clouddrive/share/2VcDYsPhkxSE3YXqedg2fqghdF9RXK7RFxdWBCZInu4](url)

It contains the dumps taken from the sample program in comment #3, one before publish started and one after. Please let me know if this works for you.

**Comment by chkr1011** [comment] 2017-12-02 13:09
This works. I downloaded the dump and analyzed it. I see 168 channel adapters. Is this possible? How much clients did you connect to that server? Or is it only one client (from your sample)?

**Comment by chkr1011** [comment] 2017-12-02 13:10
Ah forget it. It was the size not the count 😄

**Comment by archerian** [comment] 2017-12-02 13:32
For 'live' debugging it might be easier if you ran the sample in comment 3. My guess is the byte[] in Serialize isn't getting garbage collected, I've seen the memory usage increase with a bigger payload.

**Comment by archerian** [comment] 2017-12-02 14:57
I did some more testing, apparently memory usage increases depending on what the broker does with the message. I have attached two versions of the  broker code I use below.

``` csharp
///
// Server program
//
using MQTTnet;
using MQTTnet.Core.Server;
using System;
using System.Text;

namespace Intercom.NET
{
    class Program
    {
        static void Main(string[] args)
        {
            // Start a MQTT server.
            IMqttServer mqttServer = new MqttFactory().CreateMqttServer();
            MqttServerOptions options = new MqttServerOptions();
            options.DefaultEndpointOptions.Port = 13571;

            mqttServer.ClientDisconnected += (s, e) =>
            {
                Console.WriteLine(DateTime.Now + " Dx: " + e.Client.ClientId);
            };
            mqttServer.ClientConnected += (s, e) =>
            {
                Console.WriteLine(DateTime.Now + " Cx: " + e.Client.ClientId);
            };
            mqttServer.ApplicationMessageReceived += (s, e) =>
            {
                Console.WriteLine(DateTime.Now + " Rx: " + e.ApplicationMessage.Topic + "  Data: " + Encoding.UTF8.GetString(e.ApplicationMessage.Payload));
            };
            mqttServer.StartAsync(options);

            Console.WriteLine(DateTime.Now + " Railedge Intercom.NET Server started, press Enter to exit.");
            Console.ReadLine();

            mqttServer.StopAsync();
           
        }

        
    }
}
```
Version with no ApplicationMessageReceived handling

``` csharp
///
// Server program
//
using MQTTnet;
using MQTTnet.Core.Server;
using System;
using System.Text;

namespace Intercom.NET
{
    class Program
    {
        static void Main(string[] args)
        {
            // Start a MQTT server.
            IMqttServer mqttServer = new MqttFactory().CreateMqttServer();
            MqttServerOptions options = new MqttServerOptions();
            options.DefaultEndpointOptions.Port = 13571;

            mqttServer.ClientDisconnected += (s, e) =>
            {
                Console.WriteLine(DateTime.Now + " Dx: " + e.Client.ClientId);
            };
            mqttServer.ClientConnected += (s, e) =>
            {
                Console.WriteLine(DateTime.Now + " Cx: " + e.Client.ClientId);
            };
            //mqttServer.ApplicationMessageReceived += (s, e) =>
            //{
            //    Console.WriteLine(DateTime.Now + " Rx: " + e.ApplicationMessage.Topic + "  Data: " + Encoding.UTF8.GetString(e.ApplicationMessage.Payload));
            //};
            mqttServer.StartAsync(options);

            Console.WriteLine(DateTime.Now + " Railedge Intercom.NET Server started, press Enter to exit.");
            Console.ReadLine();

            mqttServer.StopAsync();
           
        }

        
    }
}
```
between the two, when I run the same client code and send several hundreds of messages, the managed heap is much larger when ApplicationMessageReceived is turned on. The managed heap has around 62 objects of type MQTTnet.Core.MqttApplicationMessage in this scenario.

Makes me wonder if there is a finite amount of time spent in processing the incoming messages that makes the client hold on to more messages in the outgoing client queue. But its async so should be place in queue and run right? Is there a possibility that if the messages come at a rate that the broker cannot handle it the queue gets extremely big?

**Comment by chkr1011** [comment] 2017-12-02 16:04
Now I am a little bit confused 😄 You start the server as in the above examples and with the attached event handler at the SERVER the CLIENT has more memory consumption?

I just saw that you use the managed client. Please try it with the regular client. If the problem is not happening there the problem is located in the managed client.

**Comment by archerian** [comment] 2017-12-02 16:26
Yes, I used the client code in Comment 3 with the two server code versions in Comment 10 and the CLIENT has more memory consumption when the SERVER ApplicationMessageReceived is turned on. 

I will check with regular client and see what happens.

**Comment by JanEggers** [comment] 2017-12-02 17:41
i added a small test if you uncomment the delay everything works fine 30MB stable. but without the delay the ClientsMsgQueue gets filled up quite fast. so i guess its not really a leak but if you publish more msgs than the network layer can handle your server eats memory for buffering.

```
[TestMethod]
        public async Task MqttServer_MemoryUsage()
        {
            var logger = new MqttNetLogger();
            var f = new MqttFactory();
            var s = f.CreateMqttServer(new[] { new MqttServerAdapter(logger) }, logger);
            var c = f.CreateMqttClient();

            try
            {
                var options = new MqttServerOptions {};

                await s.StartAsync(options);
                
                s.ApplicationMessageReceived += (sender, args) => {

                };

                await c.ConnectAsync(new MqttClientOptions()
                {
                    ChannelOptions = new MqttClientTcpOptions()
                    {
                        Server = "localhost"
                    }
                });

                await c.SubscribeAsync(new TopicFilter("#"));

                while (true)
                {
                    await s.PublishAsync(new MqttApplicationMessage()
                    {
                        Payload = new byte[10000],
                        Topic = "Any"
                    });

                    //await Task.Delay(TimeSpan.FromMilliseconds(10));
                }
            }
            finally
            {
                await s.StopAsync();
            }
        }
```

**Comment by JanEggers** [comment] 2017-12-02 17:45
also a screenshot from vs memory diagnostics would help to analyse problems.

![image](https://user-images.githubusercontent.com/6747376/33518166-f9383de4-d790-11e7-9675-993b752c1ef5.png)

**Comment by archerian** [comment] 2017-12-02 19:25
@JanEggers if the queue becomes bigger would it not be garbage collected after some time after the packets are sent?

**Comment by JanEggers** [comment] 2017-12-03 01:05
that depends on wether there is a message peak that is temporary buffered or there are constantly more messanges than the network can handle

**Comment by archerian** [comment] 2017-12-06 23:22
Tried with regular client, there is no huge memory gain as seen in ManagedClient when sending messages at the same size/rate.

**Comment by chkr1011** [comment] 2017-12-07 12:01
Did you use the storage etc. of the managed client?

**Comment by archerian** [comment] 2017-12-09 05:22
no storage, I just create a managed client, publish and subscribe.

**Comment by chkr1011** [comment] 2017-12-14 20:21
@archerian Please try again with the latest RC from nuget. Some bugs are fixed in the _ManagedClient_ which may also fix the memory issue.

**Comment by chkr1011** [comment] 2018-01-21 14:00
I close this ticket because I assume it is fixed because I got no reply. If this is wrong please reopen the ticket.

Best regards
Christian

**Closed by chkr1011** 2018-01-21 14:00 UTC
