### ISSUE TITLE
After hours MqttNet AspNetCore Server loops in MqttConnectionContext.ReceivePacketAsync

### ISSUE THREAD

**Issue by ChristianRiedl** [chkr1011/MQTTnet#953] opened 2020-07-09 09:03 UTC
### Describe the bug
After running about one day normally I noticed that my AspNetCore app with embedded MQTTNet Web server (latest version) creates high load. One thread is looping and makes one CPU 100 % busy. The load of the server is very low and constant.

I was able to create a stack dump of this situation 

```
        System.IO.Pipelines.dll!System.IO.Pipelines.Pipe.ReadAsync(System.Threading.CancellationToken token)	Unknown
 	System.IO.Pipelines.dll!System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(System.Threading.CancellationToken cancellationToken)	Unknown
 	MQTTnet.AspNetCore.dll!MQTTnet.AspNetCore.MqttConnectionContext.ReceivePacketAsync(System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken)	Unknown
 	[Resuming Async Method]	
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<MQTTnet.Packets.MqttBasePacket>.AsyncStateMachineBox<MQTTnet.AspNetCore.MqttConnectionContext.<ReceivePacketAsync>d__37>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread threadPoolThread, System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<MQTTnet.Packets.MqttBasePacket>.AsyncStateMachineBox<MQTTnet.AspNetCore.MqttConnectionContext.<ReceivePacketAsync>d__37>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.AsyncStateMachineBox<MQTTnet.AspNetCore.MqttConnectionContext.<ReceivePacketAsync>d__37>.ExecuteFromThreadPool(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	[Async Call Stack]	
 	[Async] MQTTnet.dll!MQTTnet.Server.MqttClientConnection.RunInternalAsync(MQTTnet.Server.MqttConnectionValidatorContext connectionValidatorContext)	Unknown
 	[Async] MQTTnet.dll!MQTTnet.Server.MqttClientSessionsManager.HandleClientConnectionAsync(MQTTnet.Adapter.IMqttChannelAdapter channelAdapter, System.Threading.CancellationToken cancellationToken)	Unknown
 	[Async] MQTTnet.AspNetCore.dll!MQTTnet.AspNetCore.MqttConnectionHandler.OnConnectedAsync(Microsoft.AspNetCore.Connections.ConnectionContext connection)	Unknown
 	[Async] Microsoft.AspNetCore.Http.Connections.dll!Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.ExecuteApplication(Microsoft.AspNetCore.Connections.ConnectionDelegate connectionDelegate)	Unknown

```

In other cases the stack trace shows a call to "AdvanceTo" function.. 

I see that you made a small change 5 days ago, you removed  a package reference : 

    <PackageReference Include="System.IO.Pipelines" Version="4.7.2" />

Do you think the problem is related with this change (System.IO.Pipelines functions are shown in the stack trace).

**Comment by JanEggers** [comment] 2020-07-16 06:15
duplicate of #788

**Closed by JanEggers** 2020-07-16 06:15 UTC
Labels: bug

**Comment by ChristianRiedl** [comment] 2020-07-29 21:05
I created latest version from github (with removed package reference "System.IO.Pipelines") and the problem  disappeared !!
