### ISSUE TITLE
Extract server into its own repository to be release and maintained independent from the client

### ISSUE THREAD

**Issue by ramonsmits** [chkr1011/MQTTnet#1070] opened 2021-01-26 20:54 UTC
### Describe your question

Extract server into its own repository to be release and maintained independently from the client. Currently, both are in the same repo where both are aligned in versioning. Most developers are likely only interested in the MQTT client.

### Which project is your question related to?

- Client
- ManagedClient
- MQTTnet.Server standalone
- Server
- Generic

**Comment by SeppPenner** [comment] 2021-01-29 08:17
This seems to be more or less a duplicate of https://github.com/chkr1011/MQTTnet/issues/1026.

**Closed** 2021-01-29 08:19 UTC
Labels: duplicate, question
