### ISSUE TITLE
Build errors in .net 5 after migration to 3.0.14

### ISSUE THREAD

**Issue by BEagle1984** [chkr1011/MQTTnet#1088] opened 2021-02-08 10:23 UTC
### Describe the bug

In my solution I've a netstandard2.1 class library that references MQTTnet and then a couple of net5 test projects that reference that class library.

As soon as I upgrade MQTTnet from v3.0.13 to v3.0.14 I start getting some weird build errors like the following one:
```
MqttProducerEndpointBuilderTests.cs(20, 59): [CS0012] The type 'MqttClientOptions' is defined in an assembly that is not referenced. You must add a reference to assembly 'MQTTnet, Version=3.0.14.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7'.
```

Directly referencing the MQTTnet nuget package in the test projects doesn't help.

No problem with v3.0.13 and v3.0.14 also seems to work if the test projects are targeting netcore3.1 instead of net5.

### Which project is your bug related to?
- Client

### Code example
See the broken branch https://github.com/BEagle1984/silverback/tree/feature/update-mqttnet-net5 (MQTTnet 3.0.14 with net5 test projects).

Here is a working branch with MQTTnet 3.0.14 and netcore3.1: https://github.com/BEagle1984/silverback/tree/feature/update-mqttnet-netcore31
And here is a working branch with MQTTnet 3.0.13 and net5: https://github.com/BEagle1984/silverback/tree/feature/net5

**Comment by juwens** [comment] 2021-02-08 11:04
Can confirm that with netstandard2.0 and net5.0 interop.
Workaround: moving both back to 3.13.

# Analysis:

There seems so be a inconsistency with the resolved/referenced assembly between netstandard and net5.
net5 resolves to `PublicKeyToken=null`
netstandard resolves to `PublicKeyToken=b69712f52770c0a7`

Both Project use 'MqttApplicationMessageReceivedEventArgs'.
At interop between both projects i get the error.
`CS0012	The type 'MqttApplicationMessageReceivedEventArgs' is defined in an assembly that is not referenced. You must add a reference to assembly 'MQTTnet, Version=3.0.14.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7'.`

## Net5.0 resolves to assembly with: **PublicKeyToken=null**
```
#region Assembly MQTTnet, Version=3.0.14.0, Culture=neutral, PublicKeyToken=null
// C:\Users\jjaehrig\.nuget\packages\mqttnet\3.0.14\lib\net5.0\MQTTnet.dll
// Decompiled with ICSharpCode.Decompiler 6.1.0.5902
#endregion
```

## Netstandard2.0 lib resolves to assembly with: **PublicKeyToken=b69712f52770c0a7**
```
#region Assembly MQTTnet, Version=3.0.14.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7
// C:\Users\jjaehrig\.nuget\packages\mqttnet\3.0.14\lib\netstandard2.0\MQTTnet.dll
// Decompiled with ICSharpCode.Decompiler 6.1.0.5902
#endregion
```

csproj contains just a plain
```
    <PackageReference Include="MQTTnet" Version="3.0.14" />
```

# Moving back to 3.0.13

Both (netstandrad2.0 and net5.0) use `PublicKeyToken=b69712f52770c0a7`

net5
```
#region Assembly MQTTnet, Version=3.0.13.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7
// C:\Users\jjaehrig\.nuget\packages\mqttnet\3.0.13\lib\netcoreapp3.1\MQTTnet.dll
// Decompiled with ICSharpCode.Decompiler 6.1.0.5902
#endregion
```

netstandard2
```
#region Assembly MQTTnet, Version=3.0.13.0, Culture=neutral, PublicKeyToken=b69712f52770c0a7
// C:\Users\jjaehrig\.nuget\packages\mqttnet\3.0.13\lib\netstandard2.0\MQTTnet.dll
// Decompiled with ICSharpCode.Decompiler 6.1.0.5902
#endregion
```

**Comment by SeppPenner** [comment] 2021-02-08 11:10
This is most probably related to https://github.com/chkr1011/MQTTnet/issues/1080.

From @chkr1011: https://github.com/chkr1011/MQTTnet/issues/1080#issuecomment-774471154

> It turns out that the build script was not properly updated for .net 5.0. I changed this. Please test RC1 of 3.0.15. @JanEggers Please let me know if the settings are fine for the ASP.NET parts.

**Comment by SeppPenner** [comment] 2021-02-08 12:36
I can confirm that. It also seems that there is no RC1 of 3.0.15 out yet from the library.

**Comment by chkr1011** [comment] 2021-02-14 13:04
Please try with RC1 of 3.0.15. It is out now.

**Comment by BEagle1984** [comment] 2021-02-15 15:40
It seems to work correctly with the 3.0.15-rc1. Well done.

**Comment by chkr1011** [comment] 2021-02-21 10:18
Closing because the issue is fixed.

**Closed by chkr1011** 2021-02-21 10:18 UTC
Labels: bug
