### ISSUE TITLE
NullReferenceException on ConnectAsync

### ISSUE THREAD

**Issue by mridah** [chkr1011/MQTTnet#907] opened 2020-04-24 12:40 UTC
### Describe your question
I tried using the sample code provided with .NET framework, but I keep getting `System.NullReferenceException` on `ConnectAsync()`

![image](https://user-images.githubusercontent.com/21169606/80212909-fe005c00-8655-11ea-9de8-61c05cbd5fc0.png)

### Which project is your question related to?
- Client

**This is my code:**

    MqttFactory factory = new MqttFactory();
    MqttClient client;

    public Form1()
    {
        InitializeComponent();
        ConnectAsync();
    }

    public async Task ConnectAsync()
    {
        client = (MqttClient)factory.CreateMqttClient();
        // I even tried using var client = factory.CreateMqttClient();
        // but got the same Error
        // though i need the variable to be global

        var options = new MqttClientOptionsBuilder()
            .WithClientId("Client1")
            .WithTcpServer("http://192.168.0.115", 1883)
            .WithCleanSession()
            .Build();

        await client.ConnectAsync(options, CancellationToken.None); // Since 3.0.5 with CancellationToken

        client.UseDisconnectedHandler(async e =>
        {
            Console.WriteLine("### DISCONNECTED FROM SERVER ###");
            await Task.Delay(TimeSpan.FromSeconds(5));
            try
            {
                await client.ConnectAsync(options, CancellationToken.None); // Since 3.0.5 with CancellationToken
            }
            catch
            {
                Console.WriteLine("### RECONNECTING FAILED ###");
            }
        });

        client.UseApplicationMessageReceivedHandler(e =>
        {
            Console.WriteLine("### RECEIVED APPLICATION MESSAGE ###");
            Task.Run(() => client.PublishAsync("/indiadel"));
        });

        client.UseConnectedHandler(async e =>
        {
            Console.WriteLine("### CONNECTED WITH SERVER ###");

            // Subscribe to a topic
            await client.SubscribeAsync(new TopicFilterBuilder().WithTopic("/indiadel").Build());

            Console.WriteLine("### SUBSCRIBED ###");

            //await PublishMessage("/indiadel", "hello world !#");
        });

    }

Am I doing something wrong ??? @chkr1011

**Comment by chkr1011** [comment] 2020-04-24 16:08
Hi,
first of all your TCP server is wrong. It will not work with the prefix "http://" in it. I was not able to reproduce the issue with _netstandard_ and regular .net framework.

But I got this exception on UWP. Are you building an UWP application?

**Comment by mridah** [comment] 2020-04-25 11:50
@chkr1011  hi, no I'm working on normal .NET Framework 4.7.2. Not using UWP.

I'm getting the same error even after removing the protocol prefix. Any other suggestion ?

**Comment by chkr1011** [comment] 2020-04-25 11:52
Please show me the output. I can see a little bit from it in the screenshot but is is cut off.
It seems that another exception is thrown before the null ref exception happens.

**Comment by mridah** [comment] 2020-04-25 12:11
Hi @chkr1011  thanks for the fast reply. I checked it again. It's not throwing any error but it's just not connecting to the broker.

Please see the working on this [Link](https://streamable.com/4u87cf)

**Comment by chkr1011** [comment] 2020-04-25 12:36
I am wondering if this can work at all. You have the connect method with a Task but you do not await it. Please try with _.Wait()_ on the returning task. Apart from that it looks good to me.

**Comment by mridah** [comment] 2020-04-25 16:45
Hey,

I changed the connection code from `await client.ConnectAsync(options, CancellationToken.None);` to `client.ConnectAsync(options, CancellationToken.None);` and it started working.

Maybe the handlers require the connection to be established beforehand.

**Comment by chkr1011** [comment] 2020-04-25 21:19
No sorry I mean the call in your constructor. Not the connect method.

**Comment by eifinger** [comment] 2020-05-04 15:40
I have the same problem when I supply a wrong server address.
I have the Mqttclient as a IHostedService in an ASP.NET app running dotnetcore3.1

```csharp
        public async Task StartAsync(CancellationToken cancellationToken)
        {
            try
            {
                await this.mqttClient.ConnectAsync(this.mqttClientOptions, cancellationToken);
            }
            catch (MqttCommunicationException e)
            {
                this.logger.LogWarning("Could not connect to MQTT Broker", e);
            }
        }
```

I get an NullReferenceException (which I cannot catch) when I use the debugger. The warning is logged.
As I said I tried to add another `catch (Exception e)` to catch the NullRefence but this never logged anything.

**Comment by chkr1011** [comment] 2020-05-04 20:50
Please try 3.0.10-rc1. The issue is fixed in that version.

**Comment by eifinger** [comment] 2020-05-05 07:44
Can confirm that the issue is fixed for me. Thank you!

**Closed** 2020-05-17 11:41 UTC
Labels: question
