### ISSUE TITLE
Ungraceful disconnect of client not recognized

### ISSUE THREAD

**Issue by RainerMueller82** [chkr1011/MQTTnet#118] opened 2017-11-22 07:00 UTC
Hi!
First I have to say THX for all your effort in this project, I really like the library and espescially the newest version with the managedclient :-).

I just tried to unplug my client in order to check the connection state in the server, it seems the server does not recognize the connection loss. I think after 1 1/2 times of the keep alive period the server should recognize that the client is not connected anymore, right?

Is this is bug?

Thx, Rainer.

**Comment by chkr1011** [comment] 2017-11-22 07:16
Hi,
thank you for your feedback.

So you start a server and a managed client and then you removed your LAN cable and the server does not react?

Is this happening with version 2.5.2?

Best regards
Christian

**Comment by RainerMueller82** [comment] 2017-11-22 07:45
Hi,

I used 2.5.1, but I just updated and it seems it's still not recognizing
the connection loss.
Also tried to set the defaultcommunicationtimeout to 5s and I've set the
keep alive in the client to 5s too.

After re-connecting the device, I got the disconnected message from the
server.

Let me know if I can help or try something ...

BR, Rainer.


2017-11-22 8:16 GMT+01:00 Christian <notifications@github.com>:

**Comment by chkr1011** [comment] 2017-11-22 21:42
@RainerMueller82 How did you disconnect your devices. I tested it with some ESP8266 devices and when they power off the server detects that very fast. Do you stop a client application or just call "Stop" in code without closing the app?

**Comment by RainerMueller82** [comment] 2017-11-23 06:30
Hi Christian,

I just unplugged the device from the network. A shutdown or stopping the
client will close the socket and therefore gracefully close the connection.
This is working as expected. I can try to send an empty "ping" message from
the server to all clients, to see if the connectiontimeout is working,
but this may be only a workaround.


2017-11-22 22:42 GMT+01:00 Christian <notifications@github.com>:

**Comment by RainerMueller82** [comment] 2017-11-24 09:11
Hi Christian!

I tried to further investigate this issue:

This is what HiveMQ states about the timeouts:

"The broker must disconnect a client, which doesn’t send PINGREQ or any
other message in one and a half times of the keep alive interval. Likewise
should the client close the connection if the response from the broker
isn’t received in a reasonable amount of time."

In your code in MqttClientSession.cs/ProcessReceivedPacketAsync, I think a
timer is needed. The timer should be resetted every time a message is
received (whether MqttPingReqPacket or any other control message).
When the timer expires, StopAsync() should be called, right?

If you want I can try if this solves the problem.
I tried the HiveMQ Broker and it seems to disconnect the client after the
1.5x keep-alive time.

Bye! Rainer.

2017-11-23 7:30 GMT+01:00 Rainer Müller <rainer.mueller@gmx.at>:

**Comment by RainerMueller82** [comment] 2017-11-24 11:14
Hi!

I added a task to your code, that checks if the keep alive time (x 1.5) has
expired since the last contact to the device.
I wanted to start the timer when a connect packet arrives. Unfortunately it
seems the connect packets are not passed through to the clientsession where
the received packets are processed.
But there is a check for disconnect || connect packets?

is this a bug?

Bye!

2017-11-24 10:11 GMT+01:00 Rainer Müller <rainer.mueller@gmx.at>:

**Comment by RainerMueller82** [comment] 2017-11-24 11:37
Ok, I started the timer when Subscription Message arrives, since the
Connect is not forwarded to the clientsession.
When I unplug the device now the Timer expires and StopAsync is called.
This seems to solve the Disconnect problem!
But its just a workaround, perhaps you can have a look at this.

Bye, Rainer.

2017-11-24 12:14 GMT+01:00 Rainer Müller <rainer.mueller@gmx.at>:

**Comment by chkr1011** [comment] 2017-11-24 12:03
Thank you for investigation. Yes this is an issue. 

The connect packet is not pushed because it is already processed tog et a valid client session (new or existing). 

I will check the implementation and fix it like you mentioned.

**Comment by schtibb** [comment] 2017-12-01 08:10
Hi, I just wanted to chime on on the praise. I really appreciate this library, it helps our small company to have a really flexible MQTT broker solution hosted in Azure. 

I have a question regarding the issue discussed above. We currently load balance the incoming MQTT connections between Cloud service worker roles running MQTTNet brokers. To publish a topic to a specific client we use the CliendId and append it to the topic. Each client subscribe to the topic with their clientId appended so only they get the topic published to them. However I'm wondering what will happen if a client get ungracefully disconnected and then load balanced to another broker, both brokers will have the ClientId/client in their ConnectedClients list. When the MQTTNet broker instance with the offline (ungracefully connected client) invokes the PublishAsync will some error/exception be raised since the only subscriber on that topic's socket is disconneted? Is there anyway to know if I try to publish to a offline subscriber?

**Comment by chkr1011** [comment] 2017-12-04 13:00
Hi @schtibb ,
at the moment there is no chance. I added the keep alive checks in version 2.6.0 but the official check code requires to wait 1.5 times the interval. So several seconds. If you code comes at that time it cannot know if the client is available or not. Even if it is it can be offline in the next second. So there is always a chance to fail. With the fixes in 2.6.0 you can shrink the time window at least. Maybe the new RPC feature (BETA at the moment) can help you because with this feature a client will send a reply. If you don't get it you can retry on different server etc.

@RainerMueller82 
I just release a RC of version 2.6.0 as a nuget package. Please let me know if this fixes the issue for you.

Best regards
Christian

**Comment by RainerMueller82** [comment] 2017-12-04 19:21
Hi!
Thank you for the fast bugfix! I will test it within the next 3-4 days and
let you know if it works!

Thx!
Rainer

Am 04.12.2017 14:00 schrieb "Christian" <notifications@github.com>:

**Comment by schtibb** [comment] 2017-12-05 11:02
Hi,

I will look into the RPC feature, sounds interesting. My idea was that when a publish is being done on the broker and the broker tries to send the topic to the subscribing client, if the client is not connected (if the socket is dead) then the broker could remove the client from the ClientsConnected list. Or perhaps this violates how the MQTT broker is supposed to work, it has to wait for the TTL * 1.5 to expire? One option would be to add a property to the class ConnecterMqttClient called something like
public bool LastCommunicationFailed { get; set; }

So if I try to publish to a client that has disconnected but where TTL has not yet expired I could still see that the last publish to the client failed. In order to save data traffic we have pretty long TTL so it would be good if it was possible to avoid having to ping/pong as often.

Kind regards,
Jonas

**Comment by chkr1011** [comment] 2017-12-14 20:20
It already works in the way you described. Also on a dead socket the client will be removed from the connected clients list but also if the specified keep alive timeout has expired and no packet was received. This is also described in the official MQTT documentation. It is possible to add a boolean value to the connected clients but then the list will get very huge containing lots of dead entries. You can also use the events of the server and build such a list on your own.

The problem is that processing the message is not synchronous. If a message is published via client or server there is no notification if another client has received the message. Also from server perspective this is not supported because the message is just queues internally and will be send later if the client reconnects (and want's to reuse the session). But the RPC is addressing this issue. I have a similar use case and the RPC is a naming convention + some async supporting code. In the end the client responds to a topic and this lets the other client know that the message was received. Otherwise it will throw a timeout exception.

Best regards
Christian

**Comment by chkr1011** [comment] 2017-12-18 13:26
Version 2.6.0 is now released.
Best regards
Christian

**Closed by chkr1011** 2017-12-18 13:26 UTC
Labels: bug

**Comment by schtibb** [comment] 2017-12-19 12:34
Perfect, 
please have a look at this possible issue I reported (ConnectionValidator returns void in 2.6.0)

Kind regards,
Jonas
