### ISSUE TITLE
Remaining length is invalid

### ISSUE THREAD

**Issue by Zuendelmeister** [chkr1011/MQTTnet#88] opened 2017-10-30 11:03 UTC
Hi again,

after getting the mqtt communication with tls and certificate to work, I tried to do the same between a arm linux machine and my laptop.
Unfortunately I get an error that I don't know how to resolve.
What am I doing wrong?
>> [1] [MqttServer] [Information]: Started.
MqttBroker started
>> [3] [MqttServer] [Error]: Remaining length is invalid.
MQTTnet.Core.Exceptions.MqttCommunicationException: Remaining length is invalid. ---> MQTTnet.Core.Exceptions.MqttProtocolViolationException: Remaining length is invalid.
   at MQTTnet.Core.Serializer.MqttPacketReader.ReadBodyLengthFromSource(Stream stream, CancellationToken cancellationToken)
   at MQTTnet.Core.Serializer.MqttPacketReader.ReadHeaderFromSource(Stream stream, CancellationToken cancellationToken)
   at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter.<ReceiveAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Core.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter.<ReceivePacketAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Core.Server.MqttClientSessionsManager.<RunClientSessionAsync>d__15.MoveNext()
>> [3] [MqttServer] [Information]: Client '': Disconnected.
>> [11] [MqttServer] [Error]: Remaining length is invalid.
MQTTnet.Core.Exceptions.MqttCommunicationException: Remaining length is invalid. ---> MQTTnet.Core.Exceptions.MqttProtocolViolationException: Remaining length is invalid.
   at MQTTnet.Core.Serializer.MqttPacketReader.ReadBodyLengthFromSource(Stream stream, CancellationToken cancellationToken)
   at MQTTnet.Core.Serializer.MqttPacketReader.ReadHeaderFromSource(Stream stream, CancellationToken cancellationToken)
   at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter.<ReceiveAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at MQTTnet.Core.Internal.TaskExtensions.<TimeoutAfter>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Core.Adapter.MqttChannelCommunicationAdapter.<ReceivePacketAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MQTTnet.Core.Server.MqttClientSessionsManager.<RunClientSessionAsync>d__15.MoveNext()
>> [11] [MqttServer] [Information]: Client '': Disconnected.

Realy don't know what to do...
Thanks again
Best regards,
Zuendelmeister

**Comment by chkr1011** [comment] 2017-10-30 18:40
Hi,
I assume this is a duplicate of #71. I will move the conversation to that ticket.
Best regards
Christian

**Closed by chkr1011** 2017-10-30 18:40 UTC
