### ISSUE TITLE
Mono IPv6 Issues

### ISSUE THREAD

**Issue by evacomaroski** [chkr1011/MQTTnet#431] opened 2018-10-08 06:37 UTC
Hello!

MQTTnet under mono seems to have an issue with an environment that lacks IPv6 - for instance, by passing ```ipv6.disable=1``` as kernel parameter.

First, when starting an MQTTnet server, the server will not start unless ```BoundInterNetworkV6Address``` is explicitly set to ```IPAddress.None``` when building the MQTT server options with ```MqttServerOptions```. This workaround suffices to make MQTTnet listen only on the IPv4 address - otherwise, the server will not start and will fail with the exception error:

````
An address incompatible with the requested protocol was used
````

Unfortunately, for the MQTTnet client part, I have not found a workaround and if the OS lacks IPv6 support, then the MQTTnet client will fail to connect with the same error.

I am unsure whether this issue pertains more to ```mono``` rather than MQTTnet but could the MQTTnet client implementation expose a way to set the IPv6 endpoint so it can be set to ```IPAddress.None``` such that the same workaround could be applied?

Thanks!

**Comment by rwbriggs** [comment] 2018-10-22 22:09
I think this is a general problem with using the MQTTnet library in a non-Windows environment.  It seems there is a problem with the initial Socket creation and initialization without an AddressFamily declaration.  Seems like it would be a simple fix.

**Comment by MicheleSartore** [comment] 2019-03-22 16:29
Hi,
I've the same problem in RPi 3 with mono 5.0.1.1 and with Debian 8.0

**Comment by chkr1011** [comment] 2019-03-22 19:42
Please try to implement your own channel factory and pass it in the constructor of the _MqttClient_.
There you can return a channel which is NOT depending on a dual mode socket (which might be only supported in .net). Another solution might me moving to .net core instead of mono.

**Comment by chkr1011** [comment] 2019-04-17 19:32
Please try with latest dev branch. You can now specify a address family and disable dual mode sockets.

**Closed by chkr1011** 2019-04-17 19:32 UTC

**Comment by MicheleSartore** [comment] 2019-05-10 17:38
Hi, 
thank's so mutch.
Can you give me an example ?
I'm using "CreateManagedMqttClient" with MqttClientOptionsBuilder but I can't find how to specify the address family and how to disable dual mode sockets.
Thank's for the support

**Comment by chkr1011** [comment] 2019-05-10 17:48
Please check the options. There you will find a property (I don't remember the exact name)?

**Comment by MicheleSartore** [comment] 2019-05-10 18:16
namespace MQTTnet.Client.Options
{
    public interface IMqttClientOptions
    {
        string ClientId { get; }
        bool? RequestResponseInformation { get; }
        bool? RequestProblemInformation { get; }
        ushort? ReceiveMaximum { get; }
        uint? MaximumPacketSize { get; }
        byte[] AuthenticationData { get; }
        string AuthenticationMethod { get; }
        uint? WillDelayInterval { get; }
        MqttApplicationMessage WillMessage { get; }
        TimeSpan? KeepAliveSendInterval { get; }
        TimeSpan KeepAlivePeriod { get; }
        TimeSpan CommunicationTimeout { get; }
        IMqttClientChannelOptions ChannelOptions { get; }
        MqttProtocolVersion ProtocolVersion { get; }
        IMqttClientCredentials Credentials { get; }
        bool CleanSession { get; }
        uint? SessionExpiryInterval { get; }
        ushort? TopicAliasMaximum { get; }
    }
}

I'm sorry :-) Here I cant' find it
It's the wrong class ?

**Comment by chkr1011** [comment] 2019-05-10 19:26
Ah sorry. It is not there. It is in the TCP options. The problem is that these are not exposed to the builder yet. So you have to parse them to TcpOptions after using the builder or create them without the builder.
