### ISSUE TITLE
3.0.5 MqttClient.UseDisconnectedHandler didn't called at server closed

### ISSUE THREAD

**Issue by shaojun** [chkr1011/MQTTnet#696] opened 2019-07-11 13:19 UTC
Hi,
I'm using **MQTTnet 3.0.5** as a client to connect to a mqtt server:

            // Create a new MQTT client.
            var factory = new MqttFactory();
            this.mqttClient = factory.CreateMqttClient(new MqttNetLogger("MyCustomId"));`
            this.mqttClient.UseDisconnectedHandler(async arg =>
            {
                this.shouldReconnect = true;
                this.logger.LogInformation("    Mqtt connection disconnected, " +
                    "AuthenticateResult: " + arg.AuthenticateResult +
                    ", ClientWasConnected: " + arg.ClientWasConnected +
                    ", exception: " + arg.Exception);
            });
            // Create TCP based options using the builder.
            var options = new MqttClientOptionsBuilder()
                .WithClientId(this.mqttClientId)
                .WithTcpServer(this.mqttServerUrl, this.mqttServerPort)
                .WithCredentials(this.mqttClientUsername, this.mqttClientPassword)
                .WithKeepAlivePeriod(new TimeSpan(0, 0, 30))
                .WithCleanSession(true)
                .Build();
                var result = await mqttClient.ConnectAsync(options);
            if (result.ResultCode == MQTTnet.Client.Connecting.MqttClientConnectResultCode.Success)
             {
                        this.logger.LogInformation("    Successfully connected to mqtt server.");
             }
            // close the mqtt server application in another machine.
            // but never see UseDisconnectedHandler called and logged.

I've also enabled the MqTTnet client logging, after leave the client app for minitues, the last logging of it is:
            

>   - MQTTnet - Stopped receiving packets. 
>   - MQTTnet - Stopped sending keep alive packets.

**Comment by chkr1011** [comment] 2019-07-11 16:51
Hi,
which version are you using?

**Comment by shaojun** [comment] 2019-07-12 01:41
it's 3.0.5

**Comment by shaojun** [comment] 2019-07-17 03:13
hi, seems it's confirmed a bug, and i think the impact should be high, do we have timeline for this?

**Comment by SeppPenner** [comment] 2019-07-17 07:21
Mhm, strange thing. I'm using the `DisconnectedHandler` in one of my projects as well and did not yet see this. It's not yet investigated. I will try to provide an example project to reproduce this. Might take some time...

**Comment by chkr1011** [comment] 2019-07-17 19:42
I don't think that this is a bug. I added a new UnitTest for this and it works. I also checked this by starting a MQTTnet.Server, connecting with the UWP test app, then hard killing the MQTTnet.Server. As expected the event is fired and written to the log.

@shaojun Please give us more context on what is happening in your app. The code you posted does not cover the things which happen after the connect etc. Please try to provide full sample code which can be tested against MQTTnet.Server to reproduce.

**Comment by SeppPenner** [comment] 2019-07-18 05:12
I just added the `bug` label because it seemed to be a bug. I'm using the project as well with some reconnect stuff on disconnect and didn't see the issue yet.

**Comment by SeppPenner** [comment] 2019-08-13 12:30
@chkr1011 I will close this now.
@shaojun If you have more log information or a full example available for us, please try to reach us again here or create a new issue.

**Closed by SeppPenner** 2019-08-13 12:30 UTC
Labels: more-information-needed, support

**Comment by tuannguyencoder2002** [comment] 2022-12-27 18:05
![image](https://user-images.githubusercontent.com/94479439/209705296-8d3f7cf4-ec11-4aca-9d31-d9527c54b2d3.png)
sorry, I am a newbie. how can i fix this bug

**Comment by SeppPenner** [comment] 2022-12-28 07:23
@tuannguyencoder2002 Take a look at the samples folder under https://github.com/dotnet/MQTTnet/tree/master/Samples, please. There you should find the basic functions.
