### ISSUE TITLE
StopAsync in MqttServer

### ISSUE THREAD

**Issue by zhudanfei** [chkr1011/MQTTnet#110] opened 2017-11-15 18:14 UTC
I built a simple demo of MQTT C/S and have a question about it.
My test step is:
1 Server Call MqttServer.StartAsync
2 Client  Call MqttClient.ConnectAsync
Then client and server can communicate with each other.
When I called MqttServer.StopAsync, I found another client cannot connect to the server, that is what I expected. But the existing client still can send/receive message to/from server.
I am wondering if there is a way to close all the client connections while stopping server.

Thanks.

**Comment by chkr1011** [comment] 2017-11-15 18:40
Hi,
thank you for sharing this issue. This is  a bug. I will have a look.

Best regards
Christian

**Comment by chkr1011** [comment] 2017-11-17 20:31
This issue is fixed in the preview version 2.5.2-rc1 (available as nuget).  Please let me know if the issue is now fixed.

**Comment by chkr1011** [comment] 2017-11-21 20:02
Version 2.5.2 is now released. If your problem still exists please reopen this ticket.

**Closed by chkr1011** 2017-11-21 20:02 UTC
Labels: bug
