### ISSUE TITLE
Inconsist behavior for MqttApplicationMessageInterceptorContext.SessionItems with server

### ISSUE THREAD

**Issue by yyjdelete** [chkr1011/MQTTnet#1037] opened 2020-11-25 01:53 UTC
### Describe the feature request
When do permission check with `ApplicationMessageInterceptor`, I found it also handle publish from server. But I didn't find an way to set MqttApplicationMessageInterceptorContext.SessionItems in that context, and found some other strange behavior.

### Which project is your feature request related to?
- Server

### Additional context
https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Server/MqttClientSessionsManager.cs#L439
1. Unlike `SessionItems` for client, which can be set during `ConnectionValidator`, seems there is no way to init `_serverSessionItems` for server, which is only used by `InterceptApplicationMessageAsync`;
2. 
for `ApplicationMessageInterceptor`: sessionItems=`_serverSessionItems` for server, and `senderConnection.Session.Items`(never null) for client;
for `UndeliveredMessageInterceptor`: use sessionItems=`null` for server, and `senderConnection.Session.Items`(never null) for client;

https://github.com/chkr1011/MQTTnet/blob/7eb6d2d1e3d0480b89cbdafe0dc4380ea5dd055c/Source/MQTTnet/Server/MqttServerEventDispatcher.cs#L111
3. Seems MqttServer.ApplicationMessageReceivedHandler will be called for server, but `MqttApplicationMessageReceivedEventArgs.ProcessingFailed` is never used, so if it's just an recv event and should use `ApplicationMessageInterceptor` for perm instead?

**Comment by chkr1011** [comment] 2020-11-25 20:21
Since the server is not "connecting" to itself there is no way to initialize these items. The only reason to have them is to have the application message interceptor always working. I can add the initial values for that dictionary to the server options so that these values are used after startup if this fits your needs.

**Comment by chkr1011** [comment] 2020-11-25 20:29
Point 2 is indeed an issue. I fixed that.
Point 3 is not relevant for undelivered messages but since the interceptor signature is the same as for message interceptor is is just there. Maybe I should consider creating a dedicated interceptor for not process messages.

**Comment by chkr1011** [comment] 2021-02-21 10:46
I close this because the issue is fixed.

**Closed by chkr1011** 2021-02-21 10:46 UTC
Labels: feature-request
