### ISSUE TITLE
Error connecting to a broker using a DNS

### ISSUE THREAD

**Issue by det-iot** [chkr1011/MQTTnet#736] opened 2019-08-06 07:35 UTC
### Describe the bug
Error while trying to connect to a MQTT broker using a public DNS to parse the broker's endpoint

### Which project is your bug related to?
- Client

### Expected behavior
The connection should be established without any problem, because if I use the MQTT broker's endpoint the connection is established  without any problem.

Also, if I use other client (apart from my app) like MQTTBox to subscribe to the same MQTT broker, the connection is established  without any problem using both: the brokers endpoint or the DNS which parse the endpoint

### Screenshots
This is the configuration of the MQTTBox using the DNS in the Host field:

![mqttbox](https://user-images.githubusercontent.com/43747751/62519717-7014e480-b82c-11e9-87d2-3500ee5308aa.jpg)

### Additional context / logging
This is the code using MQTTNet to establish the connection which work with the endpoint but no with the DNS

```
          IMqttClientOptions optionsSubscriber = new MqttClientOptionsBuilder()
                                .WithTcpServer(MQTTconfigSubscriber.Servidor)
                                .WithClientId(MQTTconfigSubscriber.Cliente)
                                .WithCredentials(MQTTconfigSubscriber.Username, MQTTconfigSubscriber.Password)
                                .WithTls()
                                .WithCleanSession(false)
                                .WithKeepAlivePeriod(System.TimeSpan.FromSeconds(60))
                                .Build();
```

This is the error message:
```
The remote certificate is invalid according to the validation procedure
```

If i comment the line `.WithTls()` (and try to connect to the DNS) I have the following error:
```
Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
```

which happens when the connection can not be established to the destiny

**Comment by SeppPenner** [comment] 2019-08-06 08:01
`The remote certificate is invalid according to the validation procedure` is a quite common error.

Check the following:

1. Are you using a self-signed certificate that is not validated by a certificate authority (CA)? --> The error tells you that the certificate couldn't be validated because you didn't validate it with the CA.
2. Does you domain name (e.g. www.mydomain.com) match the definition in the certificate? --> If not, this will never work, they need to match exactly.

**Comment by SeppPenner** [comment] 2019-08-06 08:08
By the way, if you want to connect to a broker running on AWS (As I assume from the image), check this https://github.com/chkr1011/MQTTnet/wiki/Client#connecting-with-amazon-aws, too.

**Comment by det-iot** [comment] 2019-08-06 09:27
Thank you @SeppPenner 

Using this:

```
.WithTls(new MqttClientOptionsBuilderTlsParameters()
{
    UseTls = true,
    AllowUntrustedCertificates = true,
    IgnoreCertificateChainErrors = false,
    IgnoreCertificateRevocationErrors = false,
    SslProtocol = System.Security.Authentication.SslProtocols.Tls12
})
```
I can connect to the broker using the DNS, so the "problem" is this line `AllowUntrustedCertificates = true,`

About the two question you asked me before, I wouldn't know to answer it. I mean, why I can connect to my broker (through DNS) using MQTTBox but no my app using MQTTnet? Does MQTTBox use any CA when I use the option `CA signed server certificate` or maybe use something like `AllowUntrustedCertificates = true` ?

Is the MQTT endpoint which amazon create when I use AmazonMQ (ActiveMQ) validated by a certificate authority and that why I can connect without problem using a trusted certificate? 

Summarizing, I would need to ask the infrastructure team to use a certificate authority CA with the DNS which parse the MQTT broker's endpoint, isn't?

**Comment by SeppPenner** [comment] 2019-08-06 09:56
> I can connect to the broker using the DNS, so the "problem" is this line AllowUntrustedCertificates = true,

Yes, because you allow untrusted connections with this line.

> I mean, why I can connect to my broker (through DNS) using MQTTBox but no my app using MQTTnet?

I guess, you're connecting to something like `https://b-1234a5b6-78cd-901e-2fgh-3i45j6k178l9-1.mq.us-east-2.amazonaws.com:8883` (Taken from the example: https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/amazon-mq-getting-started.html). Or do you use a custom domain for this like e.g. `mydomain.com` and connect to `mydomain.com:8883`? 

>  Does MQTTBox use any CA when I use the option CA signed server certificate or maybe use something like AllowUntrustedCertificates = true ?

I haven't used it and cannot give you an answer here. You might want to try another client as well to verify this (e.g. [Mqtt.fx](https://mqttfx.jensd.de/)).

> Is the MQTT endpoint which amazon create when I use AmazonMQ (ActiveMQ) validated by a certificate authority

When they give you a domain name (like `https://b-1234a5b6-78cd-901e-2fgh-3i45j6k178l9-1.mq.us-east-2.amazonaws.com:8883`), I would say yes.

>Summarizing, I would need to ask the infrastructure team to use a certificate authority CA with the DNS which parse the MQTT broker's endpoint, isn't?

This depends. I still don't know if you're using a custom domain or the one Amazon uses (From the example above). If you're using a custom domain, then you should easily get the domain certificate and be able to check what it's issued for and if this matches your connection details.

The problem is that I cannot give you more ideas as this most of the time depends on the exact setup...

**Comment by det-iot** [comment] 2019-08-06 10:50
> I guess, you're connecting to something like` https://b-1234a5b6-78cd-901e-2fgh-3i45j6k178l9-1.mq.us-east-2.amazonaws.com:8883` (Taken from the example: https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/amazon-mq-getting-started.html). Or do you use a custom domain for this like e.g. mydomain.com and connect to mydomain.com:8883?

I'm trying to connect using both from my app with MQTTnet:

- <...>.mq.us-east-2.amazonaws.com:8883 : I can establish the connection without any problem

- custom domain (mydomain.com) : I can only establish the connection if I set `AllowUntrustedCertificates = true`

As you said to me, I have also tried to connect with mqttfx with the following configuration:

![mqttfx](https://user-images.githubusercontent.com/43747751/62533990-436ec600-b848-11e9-9f52-f82ebc83ab79.jpg)

- <...>.mq.us-east-2.amazonaws.com:8883 : I can establish the connection without any problem

- custom domain (mydomain.com) :  I can establish the connection without any problem

So, why I can connect to my custom domain using MQTTbox and mqttfx and not with my app using MQTTnet? 

Could also mqttfx use something like  `AllowUntrustedCertificates = true` as default?

Thank you.

**Comment by SeppPenner** [comment] 2019-08-06 11:02
I have tried this with a local server and MQTT.fx. It seems like the software really ignores the certificate errors...

Nevertheless, you still have some issues with the domain then. How do you handle this? A reverse proxy for `mydomain.com` --> `somebullshit.mq.us-east-2.amazonaws.com:8883`?

Maybe you can talk to someone who has knowledge in infrastructure and you have to configure some re-write rules in the proxy (But I'm not an expert in this...)

**Comment by det-iot** [comment] 2019-08-06 11:12
Thank you @SeppPenner for your help. I will try if someone from infrastructure  can deal with it

**Comment by SeppPenner** [comment] 2019-09-05 09:02
@det-iot Did you manage to solve this issue? I would like to close it because in my opinion there is nothing we can do here because it's a network problem (or an issue with your setup) and not directly related to the package.

**Comment by SeppPenner** [comment] 2019-09-25 07:19
@det-iot Feel free to contact us if this issue is still present.

**Closed by SeppPenner** 2019-09-25 07:19 UTC
Labels: support
