### ISSUE TITLE
Publish not working

### ISSUE THREAD

**Issue by schtibb** [chkr1011/MQTTnet#113] opened 2017-11-16 12:00 UTC
Hi,

For some reason Publish doesn't seem to work, what am I doing wrong? I create an Instance of MqttServer and then I run StartAsync on it. Later on I invoke publish on that instance. I use the delegate method/event ApplicationMessageReceived on MqttServer to intercept messages. When I publish this event is fired, but nothing is received by the subscribing client.

I use MQTTNet 2.4. No clients connected to the broker receives the topic.

`
using MQTTnet;
using MQTTnet.Core.Protocol;
using MQTTnet.Core.Server;
using Services.Interfaces;

namespace Services
{
    public class MqttServerService : IMqttServerService
    {        
        private const int MillisecondsTimeout = 10000;

        public IMqttServer MqttServer { get; set; }

        public MqttServerService()
        {
            
            var options = new MqttServerOptions
            {
                ConnectionValidator = c =>
                {
                    if (c.ClientId.Length < 10)
                    {
                        return MqttConnectReturnCode.ConnectionRefusedIdentifierRejected;
                    }

                    if (c.Username != "xxxxxx")
                    {
                        return MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
                    }

                    if (c.Password != "xxxxxxx")
                    {
                        return MqttConnectReturnCode.ConnectionRefusedBadUsernameOrPassword;
                    }
                    return MqttConnectReturnCode.ConnectionAccepted;
                }
            };
            MqttServer = new MqttServerFactory().CreateMqttServer(options);
        }
        public void Start()
        {
            var task = MqttServer.StartAsync();            
            task.Wait();            
        }

        public void Stop()
        {
            var task = MqttServer.StopAsync();            
            task.Wait(MillisecondsTimeout);
        }

    }
}

...OutgoingMqttTopicService.cs

_mqttServerService.MqttServer.Publish(new MqttApplicationMessage(topic,outgoingMqttTopic.Payload,(MqttQualityOfServiceLevel) outgoingMqttTopic.Qos,outgoingMqttTopic.Retain));

... RmsMqttClientService.cs

using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using fleetech.Common.Interfaces;
using MQTTnet.Core.Server;
using Services.Interfaces;

namespace Services
{
    public class RmsMqttClientService : IRmsMqttClientService
    {
        
        private readonly ILoggingService _loggingService;
        
        private readonly IMqttServerService _mqttServerService;
        private readonly IIoCContainer _iocContainer;
        private readonly ConcurrentDictionary<int,Task> _tasks;
        private bool _isRunning;
        private IEnumerable<ISubscriptionService> _subscriptionServices;
        private Dictionary<string, ISubscriptionService> _subscriptionServicesByTopic;

        public RmsMqttClientService(ILoggingService loggingService,IMqttServerService mqttServerService,IIoCContainer iocContainer)
        {            
            _loggingService = loggingService;                    
            _mqttServerService = mqttServerService;
            _iocContainer = iocContainer;
            _tasks = new ConcurrentDictionary<int,Task>();                                        
        }

        public void Start()
        {
            if (_isRunning)
                return;
            
            _loggingService.Debug("Starting RmsMqttClientService");
            _subscriptionServices =  _iocContainer.ResolveIEnumerable<ISubscriptionService>().ToList();
            if (_subscriptionServices != null)
            {
                foreach (var subscriptionService in _subscriptionServices)
                {
                    subscriptionService.Start();
                }
            }

            _subscriptionServicesByTopic = _subscriptionServices.ToDictionary(subscriptionService => subscriptionService.Topic,subscriptionService=> subscriptionService);
            _mqttServerService.MqttServer.ApplicationMessageReceived += MqttServerOnApplicationMessageReceived; 
            _isRunning = true;
        }

        public void Stop()
        {
            _loggingService.Debug("Stopping RmsMqttClientService");
            _mqttServerService.MqttServer.ApplicationMessageReceived -= MqttServerOnApplicationMessageReceived;
            
            if (_subscriptionServices != null)
            {
                foreach (var subscriptionService in _subscriptionServices)
                {
                    subscriptionService.Stop();
                }
            }

            Task.WaitAll(_tasks.Values.ToArray());
            _tasks.Clear();

            _isRunning = false;
        }
        
        private void MqttServerOnApplicationMessageReceived(object sender, MqttApplicationMessageReceivedEventArgs mqttApplicationMessageReceivedEventArgs)
        {
            if (_subscriptionServices == null) return;
            if (_subscriptionServicesByTopic.TryGetValue(
                mqttApplicationMessageReceivedEventArgs.ApplicationMessage.Topic, out var subscriptionService))
            {

                var task = subscriptionService?.Process(mqttApplicationMessageReceivedEventArgs.ApplicationMessage.Payload);
                if (task == null) return;

                _tasks.TryAdd(task.Id, task);
                task.ContinueWith(a => _tasks.TryRemove(a.Id, out var deletedTask));
            }
        }

    }
}

`

**Comment by schtibb** [comment] 2017-11-16 12:30
I figured out what the issue was. The client wasn't subscribing to the same QoS level. This might be the correct behavior but both Mosquitto and GnatMQ will publish the message even if the subscription has a different QoS level.

**Comment by schtibb** [comment] 2017-11-16 12:36
I think this is a bug, 

The subscriber sets the "Maximum QOS level they will receive". 

"For example, if a message is published at QoS 2 and a client is subscribed with QoS 0, the message will be delivered to that client with QoS 0."

It seems that MQTTNet will just ignore publishing the topic if the QoS mismatch.

**Comment by chkr1011** [comment] 2017-11-16 17:44
Hi, thanks for sharing.
Yes this is a bug and show work in the way you described. This will be fixed in v2.5.2.

Best regards
Christian

**Comment by chkr1011** [comment] 2017-11-17 20:31
This issue is fixed in the preview version 2.5.2-rc1 (available as nuget).  Please let me know if the issue is now fixed.

**Comment by chkr1011** [comment] 2017-11-21 20:06
Version 2.5.2 is now released. If your problem still exists please reopen this ticket.

**Closed by chkr1011** 2017-11-21 20:06 UTC
Labels: bug
