### ISSUE TITLE
MqttCommunicationException after client connect

### ISSUE THREAD

**Issue by chall3ng3r** [chkr1011/MQTTnet#91] opened 2017-11-06 17:14 UTC
Hello,

I am using this library and have tried both v2.4 (nuget and master branch). On my laptop, it works when its connected to WiFi (internet) and ethernet cable (IP camera). 

When I test it without WiFi and only IP camera connected via ethernet, MQTT client connects and disconnects immediately with following exception:

```
2017-11-06 16:54:46.2571 | DEBUG | ### CONNECTED TO SERVER ### 
2017-11-06 16:54:46.2571 | DEBUG | ### DISCONNECTED FROM SERVER ### 
2017-11-06 16:54:46.3551 | ERROR | mqttClient.Connected 
EXCEPTION: MQTTnet.Core.Exceptions.MqttCommunicationException: The client is not connected.
   at MQTTnet.Core.Client.MqttClient.ThrowIfNotConnected()
   at MQTTnet.Core.Client.MqttClient.<SubscribeAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UVSS_App.FormUVSS.<<-ctor>b__31_0>d.MoveNext() in D:\Projects

```

The system where the app is going to be deployed only have ethernet connection without internet. Same issue, connection is established but disconnected immediately. 

I have enabled anonymous login on mosquitto service running on same laptop (localhost), but it still does the same thing. I am not binding mqtt server to any IP, it works only on my laptop with I have both WiFi and ethernet cable connected.

What could be the reason for such behavior? any pointers?

**Comment by chkr1011** [comment] 2017-11-06 18:35
Hi,
thank for your bug report.

We fixed several connection issues in the upcoming version 2.5. Probably this issue is fixed then as well. 
Is it possible for you to test it with the latest _develop_ branch? The API has some breaking changes but in the test app are some examples. The Wiki will be updated once the new version is released.
Do you also have some more information? Is it a UWP app or netstandard? In general a internet connection should not  be required. 

Best regards
Christian

**Comment by chall3ng3r** [comment] 2017-11-07 11:08
Thanks for your reply,

I checked out develop branch but didn't used it yet. Will try and report how it goes.

My app is .net 4.6 based, compiled for x64. It does same when compiled for x86, so I guess that's not the issue.

**Comment by chkr1011** [comment] 2017-11-17 20:33
This issue is fixed in the preview version 2.5.2-rc1 (available as nuget).  Please let me know if the issue is now fixed.

**Comment by chkr1011** [comment] 2017-11-21 20:02
Version 2.5.2 is now released. If your problem still exists please reopen this ticket.

**Closed by chkr1011** 2017-11-21 20:02 UTC
Labels: bug

**Comment by chall3ng3r** [comment] 2017-11-24 20:22
Using the latest version from nuget, and issue seems to be fixed :)
